desc = "Timer Group(TIMG)"
name = "timg"
prefix = "TIMG"
#alias = ""

[[regs]]
name = "T0CONFIG"
desc = "Timer 0 configuration register"
offset = 0x0000

	[[regs.fields]]
	name = "ALARM_EN"
	desc = "Configures whether or not to enable the timer 0 alarm function. This bit will be automatically cleared once an alarm occurs."
	bits = "10"
	reset = 0x0
	access = "R/W/SC"

	[[regs.fields]]
	name = "DIVCNT_RST"
	desc = "Configures whether or not to reset the timer 0 ’s clock divider counter."
	bits = "11"
	reset = 0x0
	access = "WT"

	[[regs.fields]]
	name = "DIVIDER"
	desc = "Represents the timer 0 clock (T0_clk) prescaler value."
	bits = "28:13"
	reset = 0x1
	access = "R/W"

	[[regs.fields]]
	name = "AUTORELOAD"
	desc = "Configures whether or not to enable the timer 0 auto-reload function at the time of alarm."
	bits = "29"
	reset = 0x1
	access = "R/W"

	[[regs.fields]]
	name = "INCREASE"
	desc = "Configures the counting direction of the timer 0 time-base counter."
	bits = "30"
	reset = 0x1
	access = "R/W"

	[[regs.fields]]
	name = "EN"
	desc = "Configures whether or not to enable the timer 0 time-base counter."
	bits = "31"
	reset = 0x0
	access = "R/W/SS/SC"

[[regs]]
name = "T0LO"
desc = "Timer 0 current value, low 32 bits"
offset = 0x0004

	[[regs.fields]]
	name = "LO"
	desc = "Represents the low 32 bits of the time-base counter of timer 0. Valid only after writing to TIMG_T0UPDATE_REG. Measurement unit: T0_clk"
	bits = "31:0"
	reset = 0x0
	access = "RO"

[[regs]]
name = "T0HI"
desc = "Timer 0 current value, high 22 bits"
offset = 0x0008

	[[regs.fields]]
	name = "HI"
	desc = "Represents the high 22 bits of the time-base counter of timer 0. Valid only after writing to TIMG_T0UPDATE_REG. Measurement unit: T0_clk."
	bits = "21:0"
	reset = 0x0
	access = "RO"

[[regs]]
name = "T0UPDATE"
desc = "Write to copy current timer value to TIMGn_T0LO_REG or TIMGn_T0HI_REG"
offset = 0x000C

	[[regs.fields]]
	name = "UPDATE"
	desc = "Configures to latch the counter value."
	bits = "31"
	reset = 0x0
	access = "R/W/SC"

[[regs]]
name = "T0ALARMLO"
desc = "Timer 0 alarm value, low 32 bits"
offset = 0x0010

	[[regs.fields]]
	name = "LO"
	desc = "Configures the low 32 bits of timer 0 alarm trigger time-base counter value. Valid only when TIMG_T0_ALARM_EN is 1. Measurement unit: T0_clk."
	bits = "31:0"
	reset = 0x0
	access = "R/W"

[[regs]]
name = "T0ALARMHI"
desc = "Timer 0 alarm value, high bits"
offset = 0x0014

	[[regs.fields]]
	name = "HI"
	desc = "Configures the high 22 bits of timer 0 alarm trigger time-base counter value. Valid only when TIMG_T0_ALARM_EN is 1. Measurement unit: T0_clk."
	bits = "21:0"
	reset = 0x0
	access = "R/W"

[[regs]]
name = "T0LOADLO"
desc = "Timer 0 reload value, low 32 bits"
offset = 0x0018

	[[regs.fields]]
	name = "LO"
	desc = "Configures low 32 bits of the value that a reload will load onto timer 0 time-base counter. Measurement unit: T0_clk."
	bits = "31:0"
	reset = 0x0
	access = "R/W"

[[regs]]
name = "T0LOADHI"
desc = "Timer 0 reload value, high 22 bits"
offset = 0x001C

	[[regs.fields]]
	name = "HI"
	desc = "Configures high 22 bits of the value that a reload will load onto timer 0 time-base counter. Measurement unit: T0_clk."
	bits = "21:0"
	reset = 0x0
	access = "R/W"

[[regs]]
name = "T0LOAD"
desc = "Write to reload timer from TIMG_T0LOADLO_REG or TIMG_T0LOADHI_REG"
offset = 0x0020

	[[regs.fields]]
	name = "LOAD"
	desc = "Write any value to trigger a timer 0 time-base counter reload."
	bits = "31:0"
	reset = 0x0
	access = "WT"

[[regs]]
name = "WDTCONFIG0"
desc = "Watchdog timer configuration register"
offset = 0x0048

	[[regs.fields]]
	name = "APPCPU_RESET_EN"
	desc = "Configures whether to mask the CPU reset generated by MWDT. Valid only when write protection is disabled."
	bits = "12"
	reset = 0x0
	access = "R/W"

	[[regs.fields]]
	name = "PROCPU_RESET_EN"
	desc = "Configures whether to mask the CPU reset generated by MWDT. Valid only when write protection is disabled."
	bits = "13"
	reset = 0x0
	access = "R/W"

	[[regs.fields]]
	name = "FLASHBOOT_MOD_EN"
	desc = "Configures whether to enable flash boot protection."
	bits = "14"
	reset = 0x1
	access = "R/W"

	[[regs.fields]]
	name = "SYS_RESET_LENGTH"
	desc = "Configures the system reset signal length. Valid only when write protection is disabled. Measurement unit: mwdt_clk."
	bits = "17:15"
	reset = 0x1
	access = "R/W"

	[[regs.fields]]
	name = "CPU_RESET_LENGTH"
	desc = "Configures the system reset signal length. Valid only when write protection is disabled. Measurement unit: mwdt_clk."
	bits = "20:18"
	reset = 0x1
	access = "R/W"

	[[regs.fields]]
	name = "CONF_UPDATE_EN"
	desc = "Configures to update the WDT configuration registers."
	bits = "22"
	reset = 0x0
	access = "WT"

	[[regs.fields]]
	name = "STG3"
	desc = "Configures the timeout action of stage 3. Valid only when write protection is disabled."
	bits = "24:23"
	reset = 0x0
	access = "R/W"

	[[regs.fields]]
	name = "STG2"
	desc = "Configures the timeout action of stage 2. Valid only when write protection is disabled."
	bits = "26:25"
	reset = 0x0
	access = "R/W"

	[[regs.fields]]
	name = "STG1"
	desc = "Configures the timeout action of stage 1. Valid only when write protection is disabled."
	bits = "28:27"
	reset = 0x0
	access = "R/W"

	[[regs.fields]]
	name = "STG0"
	desc = "Configures the timeout action of stage 0. Valid only when write protection is disabled."
	bits = "30:29"
	reset = 0x0
	access = "R/W"

	[[regs.fields]]
	name = "EN"
	desc = "Configures whether or not to enable the MWDT. Valid only when write protection is disabled."
	bits = "31"
	reset = 0x0
	access = "R/W"

[[regs]]
name = "WDTCONFIG1"
desc = "Watchdog timer prescaler register"
offset = 0x004C

	[[regs.fields]]
	name = "DIVCNT_RST"
	desc = "Configures whether to reset WDT’s clock divider counter."
	bits = "0"
	reset = 0x0
	access = "WT"

	[[regs.fields]]
	name = "CLK_PRESCALE"
	desc = "Configures MWDT clock prescaler value. Valid only when write protection is disabled. MWDT clock period = MWDT’s clock source period * TIMG_WDT_CLK_PRESCALE."
	bits = "31:16"
	reset = 0x1
	access = "R/W"

[[regs]]
name = "WDTCONFIG2"
desc = "Watchdog timer stage 0 timeout value"
offset = 0x0050

	[[regs.fields]]
	name = "STG0_HOLD"
	desc = "Configures the stage 0 timeout value. Valid only when write protection is disabled. Measurement unit: mwdt_clk."
	bits = "31:0"
	reset = 26000000
	access = "R/W"

[[regs]]
name = "WDTCONFIG3"
desc = "Watchdog timer stage 1 timeout value"
offset = 0x0054

	[[regs.fields]]
	name = "STG1_HOLD"
	desc = "Configures the stage 1 timeout value. Valid only when write protection is disabled. Measurement unit: mwdt_clk."
	bits = "31:0"
	reset = 0x7ffffff
	access = "R/W"

[[regs]]
name = "WDTCONFIG4"
desc = "Watchdog timer stage 2 timeout value"
offset = 0x0058

	[[regs.fields]]
	name = "STG2_HOLD"
	desc = "Configures the stage 2 timeout value. Valid only when write protection is disabled. Measurement unit: mwdt_clk."
	bits = "31:0"
	reset = 0x0fffff
	access = "R/W"

[[regs]]
name = "WDTCONFIG5"
desc = "Watchdog timer stage 3 timeout value"
offset = 0x005C

	[[regs.fields]]
	name = "STG3_HOLD"
	desc = "Configures the stage 3 timeout value. Valid only when write protection is disabled. Measurement unit: mwdt_clk."
	bits = "31:0"
	reset = 0x0fffff
	access = "R/W"

[[regs]]
name = "WDTFEED"
desc = "Write to feed the watchdog timer"
offset = 0x0060

	[[regs.fields]]
	name = "FEED"
	desc = "Write any value to feed the MWDT. Valid only when write protection is disabled."
	bits = "31:0"
	reset = 0x0
	access = "WT"

[[regs]]
name = "WDTWPROTECT"
desc = "Watchdog write protect register"
offset = 0x0064

	[[regs.fields]]
	name = "WKEY"
	desc = "Configures a different value than its reset value to enable write protection."
	bits = "31:0"
	reset = 0x50d83aa1
	access = "R/W"

[[regs]]
name = "RTCCALICFG0"
desc = "RTC frequency calculation configuration register 0"
offset = 0x0068

	[[regs.fields]]
	name = "START_CYCLING"
	desc = "Configures the frequency calculation mode."
	bits = "12"
	reset = 0x1
	access = "R/W"

	[[regs.fields]]
	name = "CLK_SEL"
	desc = "Configures to select the clock to be calibrated"
	bits = "14:13"
	reset = 0x0
	access = "R/W"

	[[regs.fields]]
	name = "RDY"
	desc = "Represents whether one-shot frequency calculation is done."
	bits = "15"
	reset = 0x0
	access = "RO"

	[[regs.fields]]
	name = "MAX"
	desc = "Configures the time to calculate RTC slow clock’s frequency. Measurement unit: XTAL_CLK."
	bits = "30:16"
	reset = 0x1
	access = "R/W"

	[[regs.fields]]
	name = "START"
	desc = "Configures whether to enable one-shot frequency calculation."
	bits = "31"
	reset = 0x0
	access = "R/W"

[[regs]]
name = "RTCCALICFG1"
desc = "RTC frequency calculation configuration register 1"
offset = 0x006C

	[[regs.fields]]
	name = "CYCLING_DATA_VLD"
	desc = "Represents whether periodic frequency calculation is done."
	bits = "0"
	reset = 0x0
	access = "RO"

	[[regs.fields]]
	name = "VALUE"
	desc = "Represents the value countered by XTAL_CLK when one-shot or periodic frequency calculation is done. It is used to calculate RTC slow clock’s frequency."
	bits = "31:7"
	reset = 0x0
	access = "RO"

[[regs]]
name = "RTCCALICFG2"
desc = "RTC frequency calculation configuration register 2"
offset = 0x0080

	[[regs.fields]]
	name = "TIMEOUT"
	desc = "Represents whether RTC frequency calculation is timeout."
	bits = "0"
	reset = 0x0
	access = "RO"

	[[regs.fields]]
	name = "TIMEOUT_RST_CNT"
	desc = "Configures the cycles that reset frequency calculation timeout."
	bits = "6:3"
	reset = 3
	access = "R/W"

	[[regs.fields]]
	name = "TIMEOUT_THRES"
	desc = "Configures the threshold value for the RTC frequency calculation timer. If the timer’s value exceeds this threshold, a timeout is triggered. Measurement unit: XTAL_CLK."
	bits = "31:7"
	reset = 0x1ffffff
	access = "R/W"

[[regs]]
name = "INT_ENA_TIMERS"
desc = "Interrupt enable bits"
offset = 0x0070

	[[regs.fields]]
	name = "T0"
	desc = "Write 1 to enable the TIMG_T0_INT interrupt."
	bits = "0"
	reset = 0x0
	access = "R/W"

	[[regs.fields]]
	name = "WDT"
	desc = "Write 1 to enable the TIMG_WDT_INT interrupt."
	bits = "1"
	reset = 0x0
	access = "R/W"

[[regs]]
name = "INT_RAW_TIMERS"
desc = "Raw interrupt status"
offset = 0x0074

	[[regs.fields]]
	name = "T0"
	desc = "The raw interrupt status bit of the TIMG_T0_INT interrupt."
	bits = "0"
	reset = 0x0
	access = "R/SS/WTC"

	[[regs.fields]]
	name = "WDT"
	desc = "The raw interrupt status bit of the TIMG_WDT_INT interrupt."
	bits = "1"
	reset = 0x0
	access = "R/SS/WTC"

[[regs]]
name = "INT_ST_TIMERS"
desc = "Masked interrupt status"
offset = 0x0078

	[[regs.fields]]
	name = "T0"
	desc = "The masked interrupt status bit of the TIMG_T0_INT interrupt."
	bits = "0"
	reset = 0x0
	access = "RO"

	[[regs.fields]]
	name = "WDT"
	desc = "The masked interrupt status bit of the TIMG_WDT_INT interrupt."
	bits = "1"
	reset = 0x0
	access = "RO"

[[regs]]
name = "INT_CLR_TIMERS"
desc = "Interrupt clear bits"
offset = 0x007C

	[[regs.fields]]
	name = "T0"
	desc = "Write 1 to clear the TIMG_T0_INT interrupt."
	bits = "0"
	reset = 0x0
	access = "WT"

	[[regs.fields]]
	name = "WDT"
	desc = "Write 1 to clear the TIMG_WDT_INT interrupt."
	bits = "1"
	reset = 0x0
	access = "WT"

[[regs]]
name = "NTIMERS_DATE"
desc = "Timer version control register"
offset = 0x00F8

	[[regs.fields]]
	name = "DATE"
	desc = "Version control register"
	bits = "27:0"
	reset = 0x2206072
	access = "R/W"

[[regs]]
name = "REGCLK"
desc = "Timer group clock gate register"
offset = 0x00FC

	[[regs.fields]]
	name = "ETM_EN"
	desc = "Configures whether to enable timer’s ETM task and event."
	bits = "28"
	reset = 0x1
	access = "R/W"

	[[regs.fields]]
	name = "WDT_CLK_IS_ACTIVE"
	desc = "Configures whether to enable WDT’s clock"
	bits = "29"
	reset = 0x1
	access = "R/W"

	[[regs.fields]]
	name = "TIMER_CLK_IS_ACTIVE"
	desc = "Configures whether to enable TIMER0`s clock"
	bits = "30"
	reset = 0x1
	access = "R/W"

	[[regs.fields]]
	name = "CLK_EN"
	desc = "Configures whether to enable gate clock signal for registers."
	bits = "31"
	reset = 0x0
	access = "R/W"
