// Do not edit: This file is automatically generated
// hash: 1e408066979383add4a7f19aea10488046b68ddf623614ba31273149fe41e425
// description: Timer Group(TIMG)

#ifndef TIMG_REGS_H
#define TIMG_REGS_H

#include <stdint.h>

/* clang-format off */

//Register Offsets

#define TIMG_T0CONFIG_OFS       ( 0x0000UL ) // Timer 0 configuration register
#define TIMG_T0LO_OFS           ( 0x0004UL ) // Timer 0 current value, low 32 bits
#define TIMG_T0HI_OFS           ( 0x0008UL ) // Timer 0 current value, high 22 bits
#define TIMG_T0UPDATE_OFS       ( 0x000CUL ) // Write to copy current timer value to TIMGn_T0LO_REG or TIMGn_T0HI_REG
#define TIMG_T0ALARMLO_OFS      ( 0x0010UL ) // Timer 0 alarm value, low 32 bits
#define TIMG_T0ALARMHI_OFS      ( 0x0014UL ) // Timer 0 alarm value, high bits
#define TIMG_T0LOADLO_OFS       ( 0x0018UL ) // Timer 0 reload value, low 32 bits
#define TIMG_T0LOADHI_OFS       ( 0x001CUL ) // Timer 0 reload value, high 22 bits
#define TIMG_T0LOAD_OFS         ( 0x0020UL ) // Write to reload timer from TIMG_T0LOADLO_REG or TIMG_T0LOADHI_REG
#define TIMG_WDTCONFIG0_OFS     ( 0x0048UL ) // Watchdog timer configuration register
#define TIMG_WDTCONFIG1_OFS     ( 0x004CUL ) // Watchdog timer prescaler register
#define TIMG_WDTCONFIG2_OFS     ( 0x0050UL ) // Watchdog timer stage 0 timeout value
#define TIMG_WDTCONFIG3_OFS     ( 0x0054UL ) // Watchdog timer stage 1 timeout value
#define TIMG_WDTCONFIG4_OFS     ( 0x0058UL ) // Watchdog timer stage 2 timeout value
#define TIMG_WDTCONFIG5_OFS     ( 0x005CUL ) // Watchdog timer stage 3 timeout value
#define TIMG_WDTFEED_OFS        ( 0x0060UL ) // Write to feed the watchdog timer
#define TIMG_WDTWPROTECT_OFS    ( 0x0064UL ) // Watchdog write protect register
#define TIMG_RTCCALICFG0_OFS    ( 0x0068UL ) // RTC frequency calculation configuration register 0
#define TIMG_RTCCALICFG1_OFS    ( 0x006CUL ) // RTC frequency calculation configuration register 1
#define TIMG_RTCCALICFG2_OFS    ( 0x0080UL ) // RTC frequency calculation configuration register 2
#define TIMG_INT_ENA_TIMERS_OFS ( 0x0070UL ) // Interrupt enable bits
#define TIMG_INT_RAW_TIMERS_OFS ( 0x0074UL ) // Raw interrupt status
#define TIMG_INT_ST_TIMERS_OFS  ( 0x0078UL ) // Masked interrupt status
#define TIMG_INT_CLR_TIMERS_OFS ( 0x007CUL ) // Interrupt clear bits
#define TIMG_NTIMERS_DATE_OFS   ( 0x00F8UL ) // Timer version control register
#define TIMG_REGCLK_OFS         ( 0x00FCUL ) // Timer group clock gate register

// Register REGs

#define TIMG_T0CONFIG_REG(base)       ( (base) + (TIMG_T0CONFIG_OFS)       )
#define TIMG_T0LO_REG(base)           ( (base) + (TIMG_T0LO_OFS)           )
#define TIMG_T0HI_REG(base)           ( (base) + (TIMG_T0HI_OFS)           )
#define TIMG_T0UPDATE_REG(base)       ( (base) + (TIMG_T0UPDATE_OFS)       )
#define TIMG_T0ALARMLO_REG(base)      ( (base) + (TIMG_T0ALARMLO_OFS)      )
#define TIMG_T0ALARMHI_REG(base)      ( (base) + (TIMG_T0ALARMHI_OFS)      )
#define TIMG_T0LOADLO_REG(base)       ( (base) + (TIMG_T0LOADLO_OFS)       )
#define TIMG_T0LOADHI_REG(base)       ( (base) + (TIMG_T0LOADHI_OFS)       )
#define TIMG_T0LOAD_REG(base)         ( (base) + (TIMG_T0LOAD_OFS)         )
#define TIMG_WDTCONFIG0_REG(base)     ( (base) + (TIMG_WDTCONFIG0_OFS)     )
#define TIMG_WDTCONFIG1_REG(base)     ( (base) + (TIMG_WDTCONFIG1_OFS)     )
#define TIMG_WDTCONFIG2_REG(base)     ( (base) + (TIMG_WDTCONFIG2_OFS)     )
#define TIMG_WDTCONFIG3_REG(base)     ( (base) + (TIMG_WDTCONFIG3_OFS)     )
#define TIMG_WDTCONFIG4_REG(base)     ( (base) + (TIMG_WDTCONFIG4_OFS)     )
#define TIMG_WDTCONFIG5_REG(base)     ( (base) + (TIMG_WDTCONFIG5_OFS)     )
#define TIMG_WDTFEED_REG(base)        ( (base) + (TIMG_WDTFEED_OFS)        )
#define TIMG_WDTWPROTECT_REG(base)    ( (base) + (TIMG_WDTWPROTECT_OFS)    )
#define TIMG_RTCCALICFG0_REG(base)    ( (base) + (TIMG_RTCCALICFG0_OFS)    )
#define TIMG_RTCCALICFG1_REG(base)    ( (base) + (TIMG_RTCCALICFG1_OFS)    )
#define TIMG_RTCCALICFG2_REG(base)    ( (base) + (TIMG_RTCCALICFG2_OFS)    )
#define TIMG_INT_ENA_TIMERS_REG(base) ( (base) + (TIMG_INT_ENA_TIMERS_OFS) )
#define TIMG_INT_RAW_TIMERS_REG(base) ( (base) + (TIMG_INT_RAW_TIMERS_OFS) )
#define TIMG_INT_ST_TIMERS_REG(base)  ( (base) + (TIMG_INT_ST_TIMERS_OFS)  )
#define TIMG_INT_CLR_TIMERS_REG(base) ( (base) + (TIMG_INT_CLR_TIMERS_OFS) )
#define TIMG_NTIMERS_DATE_REG(base)   ( (base) + (TIMG_NTIMERS_DATE_OFS)   )
#define TIMG_REGCLK_REG(base)         ( (base) + (TIMG_REGCLK_OFS)         )

// Register Bits

// TIMG_T0CONFIG
#define TIMG_T0CONFIG_DESC "Timer 0 configuration register"

#ifndef __ASSEMBLY__

union timg_t0config {
	uint32_t raw;

	struct {
		uint32_t rsvd0      : 10;
		uint32_t alarm_en   : 1;
		uint32_t divcnt_rst : 1;
		uint32_t rsvd1      : 1;
		uint32_t divider    : 16;
		uint32_t autoreload : 1;
		uint32_t increase   : 1;
		uint32_t en         : 1;
	};
};

#endif // __ASSEMBLY__

#define TIMG_T0CONFIG_ALARM_EN_DESC       "Configures whether or not to enable the timer 0 alarm function. This bit will be automatically cleared once an alarm occurs."
#define TIMG_T0CONFIG_ALARM_EN_SHIFT      ( 10 )
#define TIMG_T0CONFIG_ALARM_EN_MASK       ( 0x00000400 )
#define TIMG_T0CONFIG_ALARM_EN_VALUE(raw) ( ((raw) & (TIMG_T0CONFIG_ALARM_EN_MASK)) >> (TIMG_T0CONFIG_ALARM_EN_SHIFT) )
#define TIMG_T0CONFIG_ALARM_EN_RAW(value) ( (value) << (TIMG_T0CONFIG_ALARM_EN_SHIFT) )

#define TIMG_T0CONFIG_DIVCNT_RST_DESC       "Configures whether or not to reset the timer 0 ’s clock divider counter."
#define TIMG_T0CONFIG_DIVCNT_RST_SHIFT      ( 11 )
#define TIMG_T0CONFIG_DIVCNT_RST_MASK       ( 0x00000800 )
#define TIMG_T0CONFIG_DIVCNT_RST_VALUE(raw) ( ((raw) & (TIMG_T0CONFIG_DIVCNT_RST_MASK)) >> (TIMG_T0CONFIG_DIVCNT_RST_SHIFT) )
#define TIMG_T0CONFIG_DIVCNT_RST_RAW(value) ( (value) << (TIMG_T0CONFIG_DIVCNT_RST_SHIFT) )

#define TIMG_T0CONFIG_DIVIDER_DESC       "Represents the timer 0 clock (T0_clk) prescaler value."
#define TIMG_T0CONFIG_DIVIDER_SHIFT      ( 13 )
#define TIMG_T0CONFIG_DIVIDER_MASK       ( 0x1FFFE000 )
#define TIMG_T0CONFIG_DIVIDER_VALUE(raw) ( ((raw) & (TIMG_T0CONFIG_DIVIDER_MASK)) >> (TIMG_T0CONFIG_DIVIDER_SHIFT) )
#define TIMG_T0CONFIG_DIVIDER_RAW(value) ( (value) << (TIMG_T0CONFIG_DIVIDER_SHIFT) )

#define TIMG_T0CONFIG_AUTORELOAD_DESC       "Configures whether or not to enable the timer 0 auto-reload function at the time of alarm."
#define TIMG_T0CONFIG_AUTORELOAD_SHIFT      ( 29 )
#define TIMG_T0CONFIG_AUTORELOAD_MASK       ( 0x20000000 )
#define TIMG_T0CONFIG_AUTORELOAD_VALUE(raw) ( ((raw) & (TIMG_T0CONFIG_AUTORELOAD_MASK)) >> (TIMG_T0CONFIG_AUTORELOAD_SHIFT) )
#define TIMG_T0CONFIG_AUTORELOAD_RAW(value) ( (value) << (TIMG_T0CONFIG_AUTORELOAD_SHIFT) )

#define TIMG_T0CONFIG_INCREASE_DESC       "Configures the counting direction of the timer 0 time-base counter."
#define TIMG_T0CONFIG_INCREASE_SHIFT      ( 30 )
#define TIMG_T0CONFIG_INCREASE_MASK       ( 0x40000000 )
#define TIMG_T0CONFIG_INCREASE_VALUE(raw) ( ((raw) & (TIMG_T0CONFIG_INCREASE_MASK)) >> (TIMG_T0CONFIG_INCREASE_SHIFT) )
#define TIMG_T0CONFIG_INCREASE_RAW(value) ( (value) << (TIMG_T0CONFIG_INCREASE_SHIFT) )

#define TIMG_T0CONFIG_EN_DESC       "Configures whether or not to enable the timer 0 time-base counter."
#define TIMG_T0CONFIG_EN_SHIFT      ( 31 )
#define TIMG_T0CONFIG_EN_MASK       ( 0x80000000 )
#define TIMG_T0CONFIG_EN_VALUE(raw) ( ((raw) & (TIMG_T0CONFIG_EN_MASK)) >> (TIMG_T0CONFIG_EN_SHIFT) )
#define TIMG_T0CONFIG_EN_RAW(value) ( (value) << (TIMG_T0CONFIG_EN_SHIFT) )

// TIMG_T0LO
#define TIMG_T0LO_DESC "Timer 0 current value, low 32 bits"

#ifndef __ASSEMBLY__

union timg_t0lo {
	uint32_t raw;

	struct {
		uint32_t lo : 32;
	};
};

#endif // __ASSEMBLY__

#define TIMG_T0LO_LO_DESC       "Represents the low 32 bits of the time-base counter of timer 0. Valid only after writing to TIMG_T0UPDATE_REG. Measurement unit: T0_clk"
#define TIMG_T0LO_LO_SHIFT      ( 0 )
#define TIMG_T0LO_LO_MASK       ( 0xFFFFFFFF )
#define TIMG_T0LO_LO_VALUE(raw) ( ((raw) & (TIMG_T0LO_LO_MASK)) >> (TIMG_T0LO_LO_SHIFT) )
#define TIMG_T0LO_LO_RAW(value) ( (value) << (TIMG_T0LO_LO_SHIFT) )

// TIMG_T0HI
#define TIMG_T0HI_DESC "Timer 0 current value, high 22 bits"

#ifndef __ASSEMBLY__

union timg_t0hi {
	uint32_t raw;

	struct {
		uint32_t hi    : 22;
		uint32_t rsvd0 : 10;
	};
};

#endif // __ASSEMBLY__

#define TIMG_T0HI_HI_DESC       "Represents the high 22 bits of the time-base counter of timer 0. Valid only after writing to TIMG_T0UPDATE_REG. Measurement unit: T0_clk."
#define TIMG_T0HI_HI_SHIFT      ( 0 )
#define TIMG_T0HI_HI_MASK       ( 0x003FFFFF )
#define TIMG_T0HI_HI_VALUE(raw) ( ((raw) & (TIMG_T0HI_HI_MASK)) >> (TIMG_T0HI_HI_SHIFT) )
#define TIMG_T0HI_HI_RAW(value) ( (value) << (TIMG_T0HI_HI_SHIFT) )

// TIMG_T0UPDATE
#define TIMG_T0UPDATE_DESC "Write to copy current timer value to TIMGn_T0LO_REG or TIMGn_T0HI_REG"

#ifndef __ASSEMBLY__

union timg_t0update {
	uint32_t raw;

	struct {
		uint32_t rsvd0  : 31;
		uint32_t update : 1;
	};
};

#endif // __ASSEMBLY__

#define TIMG_T0UPDATE_UPDATE_DESC       "Configures to latch the counter value."
#define TIMG_T0UPDATE_UPDATE_SHIFT      ( 31 )
#define TIMG_T0UPDATE_UPDATE_MASK       ( 0x80000000 )
#define TIMG_T0UPDATE_UPDATE_VALUE(raw) ( ((raw) & (TIMG_T0UPDATE_UPDATE_MASK)) >> (TIMG_T0UPDATE_UPDATE_SHIFT) )
#define TIMG_T0UPDATE_UPDATE_RAW(value) ( (value) << (TIMG_T0UPDATE_UPDATE_SHIFT) )

// TIMG_T0ALARMLO
#define TIMG_T0ALARMLO_DESC "Timer 0 alarm value, low 32 bits"

#ifndef __ASSEMBLY__

union timg_t0alarmlo {
	uint32_t raw;

	struct {
		uint32_t lo : 32;
	};
};

#endif // __ASSEMBLY__

#define TIMG_T0ALARMLO_LO_DESC       "Configures the low 32 bits of timer 0 alarm trigger time-base counter value. Valid only when TIMG_T0_ALARM_EN is 1. Measurement unit: T0_clk."
#define TIMG_T0ALARMLO_LO_SHIFT      ( 0 )
#define TIMG_T0ALARMLO_LO_MASK       ( 0xFFFFFFFF )
#define TIMG_T0ALARMLO_LO_VALUE(raw) ( ((raw) & (TIMG_T0ALARMLO_LO_MASK)) >> (TIMG_T0ALARMLO_LO_SHIFT) )
#define TIMG_T0ALARMLO_LO_RAW(value) ( (value) << (TIMG_T0ALARMLO_LO_SHIFT) )

// TIMG_T0ALARMHI
#define TIMG_T0ALARMHI_DESC "Timer 0 alarm value, high bits"

#ifndef __ASSEMBLY__

union timg_t0alarmhi {
	uint32_t raw;

	struct {
		uint32_t hi    : 22;
		uint32_t rsvd0 : 10;
	};
};

#endif // __ASSEMBLY__

#define TIMG_T0ALARMHI_HI_DESC       "Configures the high 22 bits of timer 0 alarm trigger time-base counter value. Valid only when TIMG_T0_ALARM_EN is 1. Measurement unit: T0_clk."
#define TIMG_T0ALARMHI_HI_SHIFT      ( 0 )
#define TIMG_T0ALARMHI_HI_MASK       ( 0x003FFFFF )
#define TIMG_T0ALARMHI_HI_VALUE(raw) ( ((raw) & (TIMG_T0ALARMHI_HI_MASK)) >> (TIMG_T0ALARMHI_HI_SHIFT) )
#define TIMG_T0ALARMHI_HI_RAW(value) ( (value) << (TIMG_T0ALARMHI_HI_SHIFT) )

// TIMG_T0LOADLO
#define TIMG_T0LOADLO_DESC "Timer 0 reload value, low 32 bits"

#ifndef __ASSEMBLY__

union timg_t0loadlo {
	uint32_t raw;

	struct {
		uint32_t lo : 32;
	};
};

#endif // __ASSEMBLY__

#define TIMG_T0LOADLO_LO_DESC       "Configures low 32 bits of the value that a reload will load onto timer 0 time-base counter. Measurement unit: T0_clk."
#define TIMG_T0LOADLO_LO_SHIFT      ( 0 )
#define TIMG_T0LOADLO_LO_MASK       ( 0xFFFFFFFF )
#define TIMG_T0LOADLO_LO_VALUE(raw) ( ((raw) & (TIMG_T0LOADLO_LO_MASK)) >> (TIMG_T0LOADLO_LO_SHIFT) )
#define TIMG_T0LOADLO_LO_RAW(value) ( (value) << (TIMG_T0LOADLO_LO_SHIFT) )

// TIMG_T0LOADHI
#define TIMG_T0LOADHI_DESC "Timer 0 reload value, high 22 bits"

#ifndef __ASSEMBLY__

union timg_t0loadhi {
	uint32_t raw;

	struct {
		uint32_t hi    : 22;
		uint32_t rsvd0 : 10;
	};
};

#endif // __ASSEMBLY__

#define TIMG_T0LOADHI_HI_DESC       "Configures high 22 bits of the value that a reload will load onto timer 0 time-base counter. Measurement unit: T0_clk."
#define TIMG_T0LOADHI_HI_SHIFT      ( 0 )
#define TIMG_T0LOADHI_HI_MASK       ( 0x003FFFFF )
#define TIMG_T0LOADHI_HI_VALUE(raw) ( ((raw) & (TIMG_T0LOADHI_HI_MASK)) >> (TIMG_T0LOADHI_HI_SHIFT) )
#define TIMG_T0LOADHI_HI_RAW(value) ( (value) << (TIMG_T0LOADHI_HI_SHIFT) )

// TIMG_T0LOAD
#define TIMG_T0LOAD_DESC "Write to reload timer from TIMG_T0LOADLO_REG or TIMG_T0LOADHI_REG"

#ifndef __ASSEMBLY__

union timg_t0load {
	uint32_t raw;

	struct {
		uint32_t load : 32;
	};
};

#endif // __ASSEMBLY__

#define TIMG_T0LOAD_LOAD_DESC       "Write any value to trigger a timer 0 time-base counter reload."
#define TIMG_T0LOAD_LOAD_SHIFT      ( 0 )
#define TIMG_T0LOAD_LOAD_MASK       ( 0xFFFFFFFF )
#define TIMG_T0LOAD_LOAD_VALUE(raw) ( ((raw) & (TIMG_T0LOAD_LOAD_MASK)) >> (TIMG_T0LOAD_LOAD_SHIFT) )
#define TIMG_T0LOAD_LOAD_RAW(value) ( (value) << (TIMG_T0LOAD_LOAD_SHIFT) )

// TIMG_WDTCONFIG0
#define TIMG_WDTCONFIG0_DESC "Watchdog timer configuration register"

#ifndef __ASSEMBLY__

union timg_wdtconfig0 {
	uint32_t raw;

	struct {
		uint32_t rsvd0            : 12;
		uint32_t appcpu_reset_en  : 1;
		uint32_t procpu_reset_en  : 1;
		uint32_t flashboot_mod_en : 1;
		uint32_t sys_reset_length : 3;
		uint32_t cpu_reset_length : 3;
		uint32_t rsvd1            : 1;
		uint32_t conf_update_en   : 1;
		uint32_t stg3             : 2;
		uint32_t stg2             : 2;
		uint32_t stg1             : 2;
		uint32_t stg0             : 2;
		uint32_t en               : 1;
	};
};

#endif // __ASSEMBLY__

#define TIMG_WDTCONFIG0_APPCPU_RESET_EN_DESC       "Configures whether to mask the CPU reset generated by MWDT. Valid only when write protection is disabled."
#define TIMG_WDTCONFIG0_APPCPU_RESET_EN_SHIFT      ( 12 )
#define TIMG_WDTCONFIG0_APPCPU_RESET_EN_MASK       ( 0x00001000 )
#define TIMG_WDTCONFIG0_APPCPU_RESET_EN_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG0_APPCPU_RESET_EN_MASK)) >> (TIMG_WDTCONFIG0_APPCPU_RESET_EN_SHIFT) )
#define TIMG_WDTCONFIG0_APPCPU_RESET_EN_RAW(value) ( (value) << (TIMG_WDTCONFIG0_APPCPU_RESET_EN_SHIFT) )

#define TIMG_WDTCONFIG0_PROCPU_RESET_EN_DESC       "Configures whether to mask the CPU reset generated by MWDT. Valid only when write protection is disabled."
#define TIMG_WDTCONFIG0_PROCPU_RESET_EN_SHIFT      ( 13 )
#define TIMG_WDTCONFIG0_PROCPU_RESET_EN_MASK       ( 0x00002000 )
#define TIMG_WDTCONFIG0_PROCPU_RESET_EN_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG0_PROCPU_RESET_EN_MASK)) >> (TIMG_WDTCONFIG0_PROCPU_RESET_EN_SHIFT) )
#define TIMG_WDTCONFIG0_PROCPU_RESET_EN_RAW(value) ( (value) << (TIMG_WDTCONFIG0_PROCPU_RESET_EN_SHIFT) )

#define TIMG_WDTCONFIG0_FLASHBOOT_MOD_EN_DESC       "Configures whether to enable flash boot protection."
#define TIMG_WDTCONFIG0_FLASHBOOT_MOD_EN_SHIFT      ( 14 )
#define TIMG_WDTCONFIG0_FLASHBOOT_MOD_EN_MASK       ( 0x00004000 )
#define TIMG_WDTCONFIG0_FLASHBOOT_MOD_EN_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG0_FLASHBOOT_MOD_EN_MASK)) >> (TIMG_WDTCONFIG0_FLASHBOOT_MOD_EN_SHIFT) )
#define TIMG_WDTCONFIG0_FLASHBOOT_MOD_EN_RAW(value) ( (value) << (TIMG_WDTCONFIG0_FLASHBOOT_MOD_EN_SHIFT) )

#define TIMG_WDTCONFIG0_SYS_RESET_LENGTH_DESC       "Configures the system reset signal length. Valid only when write protection is disabled. Measurement unit: mwdt_clk."
#define TIMG_WDTCONFIG0_SYS_RESET_LENGTH_SHIFT      ( 15 )
#define TIMG_WDTCONFIG0_SYS_RESET_LENGTH_MASK       ( 0x00038000 )
#define TIMG_WDTCONFIG0_SYS_RESET_LENGTH_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG0_SYS_RESET_LENGTH_MASK)) >> (TIMG_WDTCONFIG0_SYS_RESET_LENGTH_SHIFT) )
#define TIMG_WDTCONFIG0_SYS_RESET_LENGTH_RAW(value) ( (value) << (TIMG_WDTCONFIG0_SYS_RESET_LENGTH_SHIFT) )

#define TIMG_WDTCONFIG0_CPU_RESET_LENGTH_DESC       "Configures the system reset signal length. Valid only when write protection is disabled. Measurement unit: mwdt_clk."
#define TIMG_WDTCONFIG0_CPU_RESET_LENGTH_SHIFT      ( 18 )
#define TIMG_WDTCONFIG0_CPU_RESET_LENGTH_MASK       ( 0x001C0000 )
#define TIMG_WDTCONFIG0_CPU_RESET_LENGTH_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG0_CPU_RESET_LENGTH_MASK)) >> (TIMG_WDTCONFIG0_CPU_RESET_LENGTH_SHIFT) )
#define TIMG_WDTCONFIG0_CPU_RESET_LENGTH_RAW(value) ( (value) << (TIMG_WDTCONFIG0_CPU_RESET_LENGTH_SHIFT) )

#define TIMG_WDTCONFIG0_CONF_UPDATE_EN_DESC       "Configures to update the WDT configuration registers."
#define TIMG_WDTCONFIG0_CONF_UPDATE_EN_SHIFT      ( 22 )
#define TIMG_WDTCONFIG0_CONF_UPDATE_EN_MASK       ( 0x00400000 )
#define TIMG_WDTCONFIG0_CONF_UPDATE_EN_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG0_CONF_UPDATE_EN_MASK)) >> (TIMG_WDTCONFIG0_CONF_UPDATE_EN_SHIFT) )
#define TIMG_WDTCONFIG0_CONF_UPDATE_EN_RAW(value) ( (value) << (TIMG_WDTCONFIG0_CONF_UPDATE_EN_SHIFT) )

#define TIMG_WDTCONFIG0_STG3_DESC       "Configures the timeout action of stage 3. Valid only when write protection is disabled."
#define TIMG_WDTCONFIG0_STG3_SHIFT      ( 23 )
#define TIMG_WDTCONFIG0_STG3_MASK       ( 0x01800000 )
#define TIMG_WDTCONFIG0_STG3_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG0_STG3_MASK)) >> (TIMG_WDTCONFIG0_STG3_SHIFT) )
#define TIMG_WDTCONFIG0_STG3_RAW(value) ( (value) << (TIMG_WDTCONFIG0_STG3_SHIFT) )

#define TIMG_WDTCONFIG0_STG2_DESC       "Configures the timeout action of stage 2. Valid only when write protection is disabled."
#define TIMG_WDTCONFIG0_STG2_SHIFT      ( 25 )
#define TIMG_WDTCONFIG0_STG2_MASK       ( 0x06000000 )
#define TIMG_WDTCONFIG0_STG2_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG0_STG2_MASK)) >> (TIMG_WDTCONFIG0_STG2_SHIFT) )
#define TIMG_WDTCONFIG0_STG2_RAW(value) ( (value) << (TIMG_WDTCONFIG0_STG2_SHIFT) )

#define TIMG_WDTCONFIG0_STG1_DESC       "Configures the timeout action of stage 1. Valid only when write protection is disabled."
#define TIMG_WDTCONFIG0_STG1_SHIFT      ( 27 )
#define TIMG_WDTCONFIG0_STG1_MASK       ( 0x18000000 )
#define TIMG_WDTCONFIG0_STG1_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG0_STG1_MASK)) >> (TIMG_WDTCONFIG0_STG1_SHIFT) )
#define TIMG_WDTCONFIG0_STG1_RAW(value) ( (value) << (TIMG_WDTCONFIG0_STG1_SHIFT) )

#define TIMG_WDTCONFIG0_STG0_DESC       "Configures the timeout action of stage 0. Valid only when write protection is disabled."
#define TIMG_WDTCONFIG0_STG0_SHIFT      ( 29 )
#define TIMG_WDTCONFIG0_STG0_MASK       ( 0x60000000 )
#define TIMG_WDTCONFIG0_STG0_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG0_STG0_MASK)) >> (TIMG_WDTCONFIG0_STG0_SHIFT) )
#define TIMG_WDTCONFIG0_STG0_RAW(value) ( (value) << (TIMG_WDTCONFIG0_STG0_SHIFT) )

#define TIMG_WDTCONFIG0_EN_DESC       "Configures whether or not to enable the MWDT. Valid only when write protection is disabled."
#define TIMG_WDTCONFIG0_EN_SHIFT      ( 31 )
#define TIMG_WDTCONFIG0_EN_MASK       ( 0x80000000 )
#define TIMG_WDTCONFIG0_EN_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG0_EN_MASK)) >> (TIMG_WDTCONFIG0_EN_SHIFT) )
#define TIMG_WDTCONFIG0_EN_RAW(value) ( (value) << (TIMG_WDTCONFIG0_EN_SHIFT) )

// TIMG_WDTCONFIG1
#define TIMG_WDTCONFIG1_DESC "Watchdog timer prescaler register"

#ifndef __ASSEMBLY__

union timg_wdtconfig1 {
	uint32_t raw;

	struct {
		uint32_t divcnt_rst   : 1;
		uint32_t rsvd0        : 15;
		uint32_t clk_prescale : 16;
	};
};

#endif // __ASSEMBLY__

#define TIMG_WDTCONFIG1_DIVCNT_RST_DESC       "Configures whether to reset WDT’s clock divider counter."
#define TIMG_WDTCONFIG1_DIVCNT_RST_SHIFT      ( 0 )
#define TIMG_WDTCONFIG1_DIVCNT_RST_MASK       ( 0x00000001 )
#define TIMG_WDTCONFIG1_DIVCNT_RST_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG1_DIVCNT_RST_MASK)) >> (TIMG_WDTCONFIG1_DIVCNT_RST_SHIFT) )
#define TIMG_WDTCONFIG1_DIVCNT_RST_RAW(value) ( (value) << (TIMG_WDTCONFIG1_DIVCNT_RST_SHIFT) )

#define TIMG_WDTCONFIG1_CLK_PRESCALE_DESC       "Configures MWDT clock prescaler value. Valid only when write protection is disabled. MWDT clock period = MWDT’s clock source period * TIMG_WDT_CLK_PRESCALE."
#define TIMG_WDTCONFIG1_CLK_PRESCALE_SHIFT      ( 16 )
#define TIMG_WDTCONFIG1_CLK_PRESCALE_MASK       ( 0xFFFF0000 )
#define TIMG_WDTCONFIG1_CLK_PRESCALE_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG1_CLK_PRESCALE_MASK)) >> (TIMG_WDTCONFIG1_CLK_PRESCALE_SHIFT) )
#define TIMG_WDTCONFIG1_CLK_PRESCALE_RAW(value) ( (value) << (TIMG_WDTCONFIG1_CLK_PRESCALE_SHIFT) )

// TIMG_WDTCONFIG2
#define TIMG_WDTCONFIG2_DESC "Watchdog timer stage 0 timeout value"

#ifndef __ASSEMBLY__

union timg_wdtconfig2 {
	uint32_t raw;

	struct {
		uint32_t stg0_hold : 32;
	};
};

#endif // __ASSEMBLY__

#define TIMG_WDTCONFIG2_STG0_HOLD_DESC       "Configures the stage 0 timeout value. Valid only when write protection is disabled. Measurement unit: mwdt_clk."
#define TIMG_WDTCONFIG2_STG0_HOLD_SHIFT      ( 0 )
#define TIMG_WDTCONFIG2_STG0_HOLD_MASK       ( 0xFFFFFFFF )
#define TIMG_WDTCONFIG2_STG0_HOLD_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG2_STG0_HOLD_MASK)) >> (TIMG_WDTCONFIG2_STG0_HOLD_SHIFT) )
#define TIMG_WDTCONFIG2_STG0_HOLD_RAW(value) ( (value) << (TIMG_WDTCONFIG2_STG0_HOLD_SHIFT) )

// TIMG_WDTCONFIG3
#define TIMG_WDTCONFIG3_DESC "Watchdog timer stage 1 timeout value"

#ifndef __ASSEMBLY__

union timg_wdtconfig3 {
	uint32_t raw;

	struct {
		uint32_t stg1_hold : 32;
	};
};

#endif // __ASSEMBLY__

#define TIMG_WDTCONFIG3_STG1_HOLD_DESC       "Configures the stage 1 timeout value. Valid only when write protection is disabled. Measurement unit: mwdt_clk."
#define TIMG_WDTCONFIG3_STG1_HOLD_SHIFT      ( 0 )
#define TIMG_WDTCONFIG3_STG1_HOLD_MASK       ( 0xFFFFFFFF )
#define TIMG_WDTCONFIG3_STG1_HOLD_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG3_STG1_HOLD_MASK)) >> (TIMG_WDTCONFIG3_STG1_HOLD_SHIFT) )
#define TIMG_WDTCONFIG3_STG1_HOLD_RAW(value) ( (value) << (TIMG_WDTCONFIG3_STG1_HOLD_SHIFT) )

// TIMG_WDTCONFIG4
#define TIMG_WDTCONFIG4_DESC "Watchdog timer stage 2 timeout value"

#ifndef __ASSEMBLY__

union timg_wdtconfig4 {
	uint32_t raw;

	struct {
		uint32_t stg2_hold : 32;
	};
};

#endif // __ASSEMBLY__

#define TIMG_WDTCONFIG4_STG2_HOLD_DESC       "Configures the stage 2 timeout value. Valid only when write protection is disabled. Measurement unit: mwdt_clk."
#define TIMG_WDTCONFIG4_STG2_HOLD_SHIFT      ( 0 )
#define TIMG_WDTCONFIG4_STG2_HOLD_MASK       ( 0xFFFFFFFF )
#define TIMG_WDTCONFIG4_STG2_HOLD_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG4_STG2_HOLD_MASK)) >> (TIMG_WDTCONFIG4_STG2_HOLD_SHIFT) )
#define TIMG_WDTCONFIG4_STG2_HOLD_RAW(value) ( (value) << (TIMG_WDTCONFIG4_STG2_HOLD_SHIFT) )

// TIMG_WDTCONFIG5
#define TIMG_WDTCONFIG5_DESC "Watchdog timer stage 3 timeout value"

#ifndef __ASSEMBLY__

union timg_wdtconfig5 {
	uint32_t raw;

	struct {
		uint32_t stg3_hold : 32;
	};
};

#endif // __ASSEMBLY__

#define TIMG_WDTCONFIG5_STG3_HOLD_DESC       "Configures the stage 3 timeout value. Valid only when write protection is disabled. Measurement unit: mwdt_clk."
#define TIMG_WDTCONFIG5_STG3_HOLD_SHIFT      ( 0 )
#define TIMG_WDTCONFIG5_STG3_HOLD_MASK       ( 0xFFFFFFFF )
#define TIMG_WDTCONFIG5_STG3_HOLD_VALUE(raw) ( ((raw) & (TIMG_WDTCONFIG5_STG3_HOLD_MASK)) >> (TIMG_WDTCONFIG5_STG3_HOLD_SHIFT) )
#define TIMG_WDTCONFIG5_STG3_HOLD_RAW(value) ( (value) << (TIMG_WDTCONFIG5_STG3_HOLD_SHIFT) )

// TIMG_WDTFEED
#define TIMG_WDTFEED_DESC "Write to feed the watchdog timer"

#ifndef __ASSEMBLY__

union timg_wdtfeed {
	uint32_t raw;

	struct {
		uint32_t feed : 32;
	};
};

#endif // __ASSEMBLY__

#define TIMG_WDTFEED_FEED_DESC       "Write any value to feed the MWDT. Valid only when write protection is disabled."
#define TIMG_WDTFEED_FEED_SHIFT      ( 0 )
#define TIMG_WDTFEED_FEED_MASK       ( 0xFFFFFFFF )
#define TIMG_WDTFEED_FEED_VALUE(raw) ( ((raw) & (TIMG_WDTFEED_FEED_MASK)) >> (TIMG_WDTFEED_FEED_SHIFT) )
#define TIMG_WDTFEED_FEED_RAW(value) ( (value) << (TIMG_WDTFEED_FEED_SHIFT) )

// TIMG_WDTWPROTECT
#define TIMG_WDTWPROTECT_DESC "Watchdog write protect register"

#ifndef __ASSEMBLY__

union timg_wdtwprotect {
	uint32_t raw;

	struct {
		uint32_t wkey : 32;
	};
};

#endif // __ASSEMBLY__

#define TIMG_WDTWPROTECT_WKEY_DESC       "Configures a different value than its reset value to enable write protection."
#define TIMG_WDTWPROTECT_WKEY_SHIFT      ( 0 )
#define TIMG_WDTWPROTECT_WKEY_MASK       ( 0xFFFFFFFF )
#define TIMG_WDTWPROTECT_WKEY_VALUE(raw) ( ((raw) & (TIMG_WDTWPROTECT_WKEY_MASK)) >> (TIMG_WDTWPROTECT_WKEY_SHIFT) )
#define TIMG_WDTWPROTECT_WKEY_RAW(value) ( (value) << (TIMG_WDTWPROTECT_WKEY_SHIFT) )

// TIMG_RTCCALICFG0
#define TIMG_RTCCALICFG0_DESC "RTC frequency calculation configuration register 0"

#ifndef __ASSEMBLY__

union timg_rtccalicfg0 {
	uint32_t raw;

	struct {
		uint32_t rsvd0         : 12;
		uint32_t start_cycling : 1;
		uint32_t clk_sel       : 2;
		uint32_t rdy           : 1;
		uint32_t max           : 15;
		uint32_t start         : 1;
	};
};

#endif // __ASSEMBLY__

#define TIMG_RTCCALICFG0_START_CYCLING_DESC       "Configures the frequency calculation mode."
#define TIMG_RTCCALICFG0_START_CYCLING_SHIFT      ( 12 )
#define TIMG_RTCCALICFG0_START_CYCLING_MASK       ( 0x00001000 )
#define TIMG_RTCCALICFG0_START_CYCLING_VALUE(raw) ( ((raw) & (TIMG_RTCCALICFG0_START_CYCLING_MASK)) >> (TIMG_RTCCALICFG0_START_CYCLING_SHIFT) )
#define TIMG_RTCCALICFG0_START_CYCLING_RAW(value) ( (value) << (TIMG_RTCCALICFG0_START_CYCLING_SHIFT) )

#define TIMG_RTCCALICFG0_CLK_SEL_DESC       "Configures to select the clock to be calibrated"
#define TIMG_RTCCALICFG0_CLK_SEL_SHIFT      ( 13 )
#define TIMG_RTCCALICFG0_CLK_SEL_MASK       ( 0x00006000 )
#define TIMG_RTCCALICFG0_CLK_SEL_VALUE(raw) ( ((raw) & (TIMG_RTCCALICFG0_CLK_SEL_MASK)) >> (TIMG_RTCCALICFG0_CLK_SEL_SHIFT) )
#define TIMG_RTCCALICFG0_CLK_SEL_RAW(value) ( (value) << (TIMG_RTCCALICFG0_CLK_SEL_SHIFT) )

#define TIMG_RTCCALICFG0_RDY_DESC       "Represents whether one-shot frequency calculation is done."
#define TIMG_RTCCALICFG0_RDY_SHIFT      ( 15 )
#define TIMG_RTCCALICFG0_RDY_MASK       ( 0x00008000 )
#define TIMG_RTCCALICFG0_RDY_VALUE(raw) ( ((raw) & (TIMG_RTCCALICFG0_RDY_MASK)) >> (TIMG_RTCCALICFG0_RDY_SHIFT) )
#define TIMG_RTCCALICFG0_RDY_RAW(value) ( (value) << (TIMG_RTCCALICFG0_RDY_SHIFT) )

#define TIMG_RTCCALICFG0_MAX_DESC       "Configures the time to calculate RTC slow clock’s frequency. Measurement unit: XTAL_CLK."
#define TIMG_RTCCALICFG0_MAX_SHIFT      ( 16 )
#define TIMG_RTCCALICFG0_MAX_MASK       ( 0x7FFF0000 )
#define TIMG_RTCCALICFG0_MAX_VALUE(raw) ( ((raw) & (TIMG_RTCCALICFG0_MAX_MASK)) >> (TIMG_RTCCALICFG0_MAX_SHIFT) )
#define TIMG_RTCCALICFG0_MAX_RAW(value) ( (value) << (TIMG_RTCCALICFG0_MAX_SHIFT) )

#define TIMG_RTCCALICFG0_START_DESC       "Configures whether to enable one-shot frequency calculation."
#define TIMG_RTCCALICFG0_START_SHIFT      ( 31 )
#define TIMG_RTCCALICFG0_START_MASK       ( 0x80000000 )
#define TIMG_RTCCALICFG0_START_VALUE(raw) ( ((raw) & (TIMG_RTCCALICFG0_START_MASK)) >> (TIMG_RTCCALICFG0_START_SHIFT) )
#define TIMG_RTCCALICFG0_START_RAW(value) ( (value) << (TIMG_RTCCALICFG0_START_SHIFT) )

// TIMG_RTCCALICFG1
#define TIMG_RTCCALICFG1_DESC "RTC frequency calculation configuration register 1"

#ifndef __ASSEMBLY__

union timg_rtccalicfg1 {
	uint32_t raw;

	struct {
		uint32_t cycling_data_vld : 1;
		uint32_t rsvd0            : 6;
		uint32_t value            : 25;
	};
};

#endif // __ASSEMBLY__

#define TIMG_RTCCALICFG1_CYCLING_DATA_VLD_DESC       "Represents whether periodic frequency calculation is done."
#define TIMG_RTCCALICFG1_CYCLING_DATA_VLD_SHIFT      ( 0 )
#define TIMG_RTCCALICFG1_CYCLING_DATA_VLD_MASK       ( 0x00000001 )
#define TIMG_RTCCALICFG1_CYCLING_DATA_VLD_VALUE(raw) ( ((raw) & (TIMG_RTCCALICFG1_CYCLING_DATA_VLD_MASK)) >> (TIMG_RTCCALICFG1_CYCLING_DATA_VLD_SHIFT) )
#define TIMG_RTCCALICFG1_CYCLING_DATA_VLD_RAW(value) ( (value) << (TIMG_RTCCALICFG1_CYCLING_DATA_VLD_SHIFT) )

#define TIMG_RTCCALICFG1_VALUE_DESC       "Represents the value countered by XTAL_CLK when one-shot or periodic frequency calculation is done. It is used to calculate RTC slow clock’s frequency."
#define TIMG_RTCCALICFG1_VALUE_SHIFT      ( 7 )
#define TIMG_RTCCALICFG1_VALUE_MASK       ( 0xFFFFFF80 )
#define TIMG_RTCCALICFG1_VALUE_VALUE(raw) ( ((raw) & (TIMG_RTCCALICFG1_VALUE_MASK)) >> (TIMG_RTCCALICFG1_VALUE_SHIFT) )
#define TIMG_RTCCALICFG1_VALUE_RAW(value) ( (value) << (TIMG_RTCCALICFG1_VALUE_SHIFT) )

// TIMG_RTCCALICFG2
#define TIMG_RTCCALICFG2_DESC "RTC frequency calculation configuration register 2"

#ifndef __ASSEMBLY__

union timg_rtccalicfg2 {
	uint32_t raw;

	struct {
		uint32_t timeout         : 1;
		uint32_t rsvd0           : 2;
		uint32_t timeout_rst_cnt : 4;
		uint32_t timeout_thres   : 25;
	};
};

#endif // __ASSEMBLY__

#define TIMG_RTCCALICFG2_TIMEOUT_DESC       "Represents whether RTC frequency calculation is timeout."
#define TIMG_RTCCALICFG2_TIMEOUT_SHIFT      ( 0 )
#define TIMG_RTCCALICFG2_TIMEOUT_MASK       ( 0x00000001 )
#define TIMG_RTCCALICFG2_TIMEOUT_VALUE(raw) ( ((raw) & (TIMG_RTCCALICFG2_TIMEOUT_MASK)) >> (TIMG_RTCCALICFG2_TIMEOUT_SHIFT) )
#define TIMG_RTCCALICFG2_TIMEOUT_RAW(value) ( (value) << (TIMG_RTCCALICFG2_TIMEOUT_SHIFT) )

#define TIMG_RTCCALICFG2_TIMEOUT_RST_CNT_DESC       "Configures the cycles that reset frequency calculation timeout."
#define TIMG_RTCCALICFG2_TIMEOUT_RST_CNT_SHIFT      ( 3 )
#define TIMG_RTCCALICFG2_TIMEOUT_RST_CNT_MASK       ( 0x00000078 )
#define TIMG_RTCCALICFG2_TIMEOUT_RST_CNT_VALUE(raw) ( ((raw) & (TIMG_RTCCALICFG2_TIMEOUT_RST_CNT_MASK)) >> (TIMG_RTCCALICFG2_TIMEOUT_RST_CNT_SHIFT) )
#define TIMG_RTCCALICFG2_TIMEOUT_RST_CNT_RAW(value) ( (value) << (TIMG_RTCCALICFG2_TIMEOUT_RST_CNT_SHIFT) )

#define TIMG_RTCCALICFG2_TIMEOUT_THRES_DESC       "Configures the threshold value for the RTC frequency calculation timer. If the timer’s value exceeds this threshold, a timeout is triggered. Measurement unit: XTAL_CLK."
#define TIMG_RTCCALICFG2_TIMEOUT_THRES_SHIFT      ( 7 )
#define TIMG_RTCCALICFG2_TIMEOUT_THRES_MASK       ( 0xFFFFFF80 )
#define TIMG_RTCCALICFG2_TIMEOUT_THRES_VALUE(raw) ( ((raw) & (TIMG_RTCCALICFG2_TIMEOUT_THRES_MASK)) >> (TIMG_RTCCALICFG2_TIMEOUT_THRES_SHIFT) )
#define TIMG_RTCCALICFG2_TIMEOUT_THRES_RAW(value) ( (value) << (TIMG_RTCCALICFG2_TIMEOUT_THRES_SHIFT) )

// TIMG_INT_ENA_TIMERS
#define TIMG_INT_ENA_TIMERS_DESC "Interrupt enable bits"

#ifndef __ASSEMBLY__

union timg_int_ena_timers {
	uint32_t raw;

	struct {
		uint32_t t0    : 1;
		uint32_t wdt   : 1;
		uint32_t rsvd0 : 30;
	};
};

#endif // __ASSEMBLY__

#define TIMG_INT_ENA_TIMERS_T0_DESC       "Write 1 to enable the TIMG_T0_INT interrupt."
#define TIMG_INT_ENA_TIMERS_T0_SHIFT      ( 0 )
#define TIMG_INT_ENA_TIMERS_T0_MASK       ( 0x00000001 )
#define TIMG_INT_ENA_TIMERS_T0_VALUE(raw) ( ((raw) & (TIMG_INT_ENA_TIMERS_T0_MASK)) >> (TIMG_INT_ENA_TIMERS_T0_SHIFT) )
#define TIMG_INT_ENA_TIMERS_T0_RAW(value) ( (value) << (TIMG_INT_ENA_TIMERS_T0_SHIFT) )

#define TIMG_INT_ENA_TIMERS_WDT_DESC       "Write 1 to enable the TIMG_WDT_INT interrupt."
#define TIMG_INT_ENA_TIMERS_WDT_SHIFT      ( 1 )
#define TIMG_INT_ENA_TIMERS_WDT_MASK       ( 0x00000002 )
#define TIMG_INT_ENA_TIMERS_WDT_VALUE(raw) ( ((raw) & (TIMG_INT_ENA_TIMERS_WDT_MASK)) >> (TIMG_INT_ENA_TIMERS_WDT_SHIFT) )
#define TIMG_INT_ENA_TIMERS_WDT_RAW(value) ( (value) << (TIMG_INT_ENA_TIMERS_WDT_SHIFT) )

// TIMG_INT_RAW_TIMERS
#define TIMG_INT_RAW_TIMERS_DESC "Raw interrupt status"

#ifndef __ASSEMBLY__

union timg_int_raw_timers {
	uint32_t raw;

	struct {
		uint32_t t0    : 1;
		uint32_t wdt   : 1;
		uint32_t rsvd0 : 30;
	};
};

#endif // __ASSEMBLY__

#define TIMG_INT_RAW_TIMERS_T0_DESC       "The raw interrupt status bit of the TIMG_T0_INT interrupt."
#define TIMG_INT_RAW_TIMERS_T0_SHIFT      ( 0 )
#define TIMG_INT_RAW_TIMERS_T0_MASK       ( 0x00000001 )
#define TIMG_INT_RAW_TIMERS_T0_VALUE(raw) ( ((raw) & (TIMG_INT_RAW_TIMERS_T0_MASK)) >> (TIMG_INT_RAW_TIMERS_T0_SHIFT) )
#define TIMG_INT_RAW_TIMERS_T0_RAW(value) ( (value) << (TIMG_INT_RAW_TIMERS_T0_SHIFT) )

#define TIMG_INT_RAW_TIMERS_WDT_DESC       "The raw interrupt status bit of the TIMG_WDT_INT interrupt."
#define TIMG_INT_RAW_TIMERS_WDT_SHIFT      ( 1 )
#define TIMG_INT_RAW_TIMERS_WDT_MASK       ( 0x00000002 )
#define TIMG_INT_RAW_TIMERS_WDT_VALUE(raw) ( ((raw) & (TIMG_INT_RAW_TIMERS_WDT_MASK)) >> (TIMG_INT_RAW_TIMERS_WDT_SHIFT) )
#define TIMG_INT_RAW_TIMERS_WDT_RAW(value) ( (value) << (TIMG_INT_RAW_TIMERS_WDT_SHIFT) )

// TIMG_INT_ST_TIMERS
#define TIMG_INT_ST_TIMERS_DESC "Masked interrupt status"

#ifndef __ASSEMBLY__

union timg_int_st_timers {
	uint32_t raw;

	struct {
		uint32_t t0    : 1;
		uint32_t wdt   : 1;
		uint32_t rsvd0 : 30;
	};
};

#endif // __ASSEMBLY__

#define TIMG_INT_ST_TIMERS_T0_DESC       "The masked interrupt status bit of the TIMG_T0_INT interrupt."
#define TIMG_INT_ST_TIMERS_T0_SHIFT      ( 0 )
#define TIMG_INT_ST_TIMERS_T0_MASK       ( 0x00000001 )
#define TIMG_INT_ST_TIMERS_T0_VALUE(raw) ( ((raw) & (TIMG_INT_ST_TIMERS_T0_MASK)) >> (TIMG_INT_ST_TIMERS_T0_SHIFT) )
#define TIMG_INT_ST_TIMERS_T0_RAW(value) ( (value) << (TIMG_INT_ST_TIMERS_T0_SHIFT) )

#define TIMG_INT_ST_TIMERS_WDT_DESC       "The masked interrupt status bit of the TIMG_WDT_INT interrupt."
#define TIMG_INT_ST_TIMERS_WDT_SHIFT      ( 1 )
#define TIMG_INT_ST_TIMERS_WDT_MASK       ( 0x00000002 )
#define TIMG_INT_ST_TIMERS_WDT_VALUE(raw) ( ((raw) & (TIMG_INT_ST_TIMERS_WDT_MASK)) >> (TIMG_INT_ST_TIMERS_WDT_SHIFT) )
#define TIMG_INT_ST_TIMERS_WDT_RAW(value) ( (value) << (TIMG_INT_ST_TIMERS_WDT_SHIFT) )

// TIMG_INT_CLR_TIMERS
#define TIMG_INT_CLR_TIMERS_DESC "Interrupt clear bits"

#ifndef __ASSEMBLY__

union timg_int_clr_timers {
	uint32_t raw;

	struct {
		uint32_t t0    : 1;
		uint32_t wdt   : 1;
		uint32_t rsvd0 : 30;
	};
};

#endif // __ASSEMBLY__

#define TIMG_INT_CLR_TIMERS_T0_DESC       "Write 1 to clear the TIMG_T0_INT interrupt."
#define TIMG_INT_CLR_TIMERS_T0_SHIFT      ( 0 )
#define TIMG_INT_CLR_TIMERS_T0_MASK       ( 0x00000001 )
#define TIMG_INT_CLR_TIMERS_T0_VALUE(raw) ( ((raw) & (TIMG_INT_CLR_TIMERS_T0_MASK)) >> (TIMG_INT_CLR_TIMERS_T0_SHIFT) )
#define TIMG_INT_CLR_TIMERS_T0_RAW(value) ( (value) << (TIMG_INT_CLR_TIMERS_T0_SHIFT) )

#define TIMG_INT_CLR_TIMERS_WDT_DESC       "Write 1 to clear the TIMG_WDT_INT interrupt."
#define TIMG_INT_CLR_TIMERS_WDT_SHIFT      ( 1 )
#define TIMG_INT_CLR_TIMERS_WDT_MASK       ( 0x00000002 )
#define TIMG_INT_CLR_TIMERS_WDT_VALUE(raw) ( ((raw) & (TIMG_INT_CLR_TIMERS_WDT_MASK)) >> (TIMG_INT_CLR_TIMERS_WDT_SHIFT) )
#define TIMG_INT_CLR_TIMERS_WDT_RAW(value) ( (value) << (TIMG_INT_CLR_TIMERS_WDT_SHIFT) )

// TIMG_NTIMERS_DATE
#define TIMG_NTIMERS_DATE_DESC "Timer version control register"

#ifndef __ASSEMBLY__

union timg_ntimers_date {
	uint32_t raw;

	struct {
		uint32_t date  : 28;
		uint32_t rsvd0 : 4;
	};
};

#endif // __ASSEMBLY__

#define TIMG_NTIMERS_DATE_DATE_DESC       "Version control register"
#define TIMG_NTIMERS_DATE_DATE_SHIFT      ( 0 )
#define TIMG_NTIMERS_DATE_DATE_MASK       ( 0x0FFFFFFF )
#define TIMG_NTIMERS_DATE_DATE_VALUE(raw) ( ((raw) & (TIMG_NTIMERS_DATE_DATE_MASK)) >> (TIMG_NTIMERS_DATE_DATE_SHIFT) )
#define TIMG_NTIMERS_DATE_DATE_RAW(value) ( (value) << (TIMG_NTIMERS_DATE_DATE_SHIFT) )

// TIMG_REGCLK
#define TIMG_REGCLK_DESC "Timer group clock gate register"

#ifndef __ASSEMBLY__

union timg_regclk {
	uint32_t raw;

	struct {
		uint32_t rsvd0               : 28;
		uint32_t etm_en              : 1;
		uint32_t wdt_clk_is_active   : 1;
		uint32_t timer_clk_is_active : 1;
		uint32_t clk_en              : 1;
	};
};

#endif // __ASSEMBLY__

#define TIMG_REGCLK_ETM_EN_DESC       "Configures whether to enable timer’s ETM task and event."
#define TIMG_REGCLK_ETM_EN_SHIFT      ( 28 )
#define TIMG_REGCLK_ETM_EN_MASK       ( 0x10000000 )
#define TIMG_REGCLK_ETM_EN_VALUE(raw) ( ((raw) & (TIMG_REGCLK_ETM_EN_MASK)) >> (TIMG_REGCLK_ETM_EN_SHIFT) )
#define TIMG_REGCLK_ETM_EN_RAW(value) ( (value) << (TIMG_REGCLK_ETM_EN_SHIFT) )

#define TIMG_REGCLK_WDT_CLK_IS_ACTIVE_DESC       "Configures whether to enable WDT’s clock"
#define TIMG_REGCLK_WDT_CLK_IS_ACTIVE_SHIFT      ( 29 )
#define TIMG_REGCLK_WDT_CLK_IS_ACTIVE_MASK       ( 0x20000000 )
#define TIMG_REGCLK_WDT_CLK_IS_ACTIVE_VALUE(raw) ( ((raw) & (TIMG_REGCLK_WDT_CLK_IS_ACTIVE_MASK)) >> (TIMG_REGCLK_WDT_CLK_IS_ACTIVE_SHIFT) )
#define TIMG_REGCLK_WDT_CLK_IS_ACTIVE_RAW(value) ( (value) << (TIMG_REGCLK_WDT_CLK_IS_ACTIVE_SHIFT) )

#define TIMG_REGCLK_TIMER_CLK_IS_ACTIVE_DESC       "Configures whether to enable TIMER0`s clock"
#define TIMG_REGCLK_TIMER_CLK_IS_ACTIVE_SHIFT      ( 30 )
#define TIMG_REGCLK_TIMER_CLK_IS_ACTIVE_MASK       ( 0x40000000 )
#define TIMG_REGCLK_TIMER_CLK_IS_ACTIVE_VALUE(raw) ( ((raw) & (TIMG_REGCLK_TIMER_CLK_IS_ACTIVE_MASK)) >> (TIMG_REGCLK_TIMER_CLK_IS_ACTIVE_SHIFT) )
#define TIMG_REGCLK_TIMER_CLK_IS_ACTIVE_RAW(value) ( (value) << (TIMG_REGCLK_TIMER_CLK_IS_ACTIVE_SHIFT) )

#define TIMG_REGCLK_CLK_EN_DESC       "Configures whether to enable gate clock signal for registers."
#define TIMG_REGCLK_CLK_EN_SHIFT      ( 31 )
#define TIMG_REGCLK_CLK_EN_MASK       ( 0x80000000 )
#define TIMG_REGCLK_CLK_EN_VALUE(raw) ( ((raw) & (TIMG_REGCLK_CLK_EN_MASK)) >> (TIMG_REGCLK_CLK_EN_SHIFT) )
#define TIMG_REGCLK_CLK_EN_RAW(value) ( (value) << (TIMG_REGCLK_CLK_EN_SHIFT) )

/* clang-format on */

#endif // TIMG_REGS_H
