// Do not edit: This file is automatically generated
// hash: ca24bdb03fc910dcb52b6cafac5b28dfaa50f86dd0c8a4aabf705c97e89e9532
// description: Watchdog Timers(WDT)

#ifndef WDT_REGS_H
#define WDT_REGS_H

#include <stdint.h>

/* clang-format off */

//Register Offsets

#define WDT_RWDT_CONFIG0_OFS  ( 0x0000UL ) // Configure the RWDT operation
#define WDT_RWDT_CONFIG1_OFS  ( 0x0004UL ) // Configure the RWDT timeout time of stage0
#define WDT_RWDT_CONFIG2_OFS  ( 0x0008UL ) // Configure the RWDT timeout time of stage1
#define WDT_RWDT_CONFIG3_OFS  ( 0x000CUL ) // Configure the RWDT timeout time of stage2
#define WDT_RWDT_CONFIG4_OFS  ( 0x0010UL ) // Configure the RWDT timeout time of stage3
#define WDT_RWDT_FEED_OFS     ( 0x0014UL ) // Configure the feed function of RWDT
#define WDT_RWDT_WPROTECT_OFS ( 0x0018UL ) // Configure the lock function of RWDT
#define WDT_SWD_CONFIG_OFS    ( 0x001CUL ) // Configure the SWD operation
#define WDT_SWD_WPROTECT_OFS  ( 0x0020UL ) // Configure the lock function of SWD
#define WDT_INT_RAW_OFS       ( 0x0024UL ) // The interrupt raw register of WDT
#define WDT_INT_ST_OFS        ( 0x0028UL ) // The interrupt status register of WDT
#define WDT_INT_ENA_OFS       ( 0x002CUL ) // The interrupt enable register of WDT
#define WDT_INT_CLR_OFS       ( 0x0030UL ) // The interrupt clear register of WDT
#define WDT_DATE_OFS          ( 0x03FCUL ) // Version control register

// Register REGs

#define WDT_RWDT_CONFIG0_REG(base)  ( (base) + (WDT_RWDT_CONFIG0_OFS)  )
#define WDT_RWDT_CONFIG1_REG(base)  ( (base) + (WDT_RWDT_CONFIG1_OFS)  )
#define WDT_RWDT_CONFIG2_REG(base)  ( (base) + (WDT_RWDT_CONFIG2_OFS)  )
#define WDT_RWDT_CONFIG3_REG(base)  ( (base) + (WDT_RWDT_CONFIG3_OFS)  )
#define WDT_RWDT_CONFIG4_REG(base)  ( (base) + (WDT_RWDT_CONFIG4_OFS)  )
#define WDT_RWDT_FEED_REG(base)     ( (base) + (WDT_RWDT_FEED_OFS)     )
#define WDT_RWDT_WPROTECT_REG(base) ( (base) + (WDT_RWDT_WPROTECT_OFS) )
#define WDT_SWD_CONFIG_REG(base)    ( (base) + (WDT_SWD_CONFIG_OFS)    )
#define WDT_SWD_WPROTECT_REG(base)  ( (base) + (WDT_SWD_WPROTECT_OFS)  )
#define WDT_INT_RAW_REG(base)       ( (base) + (WDT_INT_RAW_OFS)       )
#define WDT_INT_ST_REG(base)        ( (base) + (WDT_INT_ST_OFS)        )
#define WDT_INT_ENA_REG(base)       ( (base) + (WDT_INT_ENA_OFS)       )
#define WDT_INT_CLR_REG(base)       ( (base) + (WDT_INT_CLR_OFS)       )
#define WDT_DATE_REG(base)          ( (base) + (WDT_DATE_OFS)          )

// Register Bits

// WDT_RWDT_CONFIG0
#define WDT_RWDT_CONFIG0_DESC "Configure the RWDT operation"

#ifndef __ASSEMBLY__

union wdt_rwdt_config0 {
	uint32_t raw;

	struct {
		uint32_t rsvd0            : 9;
		uint32_t pause_in_slp     : 1;
		uint32_t rsvd1            : 1;
		uint32_t procpu_reset_en  : 1;
		uint32_t flashboot_mod_en : 1;
		uint32_t sys_reset_length : 3;
		uint32_t cpu_reset_length : 3;
		uint32_t stg3             : 3;
		uint32_t stg2             : 3;
		uint32_t stg1             : 3;
		uint32_t stg0             : 3;
		uint32_t en               : 1;
	};
};

#endif // __ASSEMBLY__

#define WDT_RWDT_CONFIG0_PAUSE_IN_SLP_DESC       "Configure whether or not pause RWDT when chip is in sleep mode."
#define WDT_RWDT_CONFIG0_PAUSE_IN_SLP_SHIFT      ( 9 )
#define WDT_RWDT_CONFIG0_PAUSE_IN_SLP_MASK       ( 0x00000200 )
#define WDT_RWDT_CONFIG0_PAUSE_IN_SLP_VALUE(raw) ( ((raw) & (WDT_RWDT_CONFIG0_PAUSE_IN_SLP_MASK)) >> (WDT_RWDT_CONFIG0_PAUSE_IN_SLP_SHIFT) )
#define WDT_RWDT_CONFIG0_PAUSE_IN_SLP_RAW(value) ( (value) << (WDT_RWDT_CONFIG0_PAUSE_IN_SLP_SHIFT) )

#define WDT_RWDT_CONFIG0_PROCPU_RESET_EN_DESC       "Configure whether or not to enable RWDT to reset CPU."
#define WDT_RWDT_CONFIG0_PROCPU_RESET_EN_SHIFT      ( 11 )
#define WDT_RWDT_CONFIG0_PROCPU_RESET_EN_MASK       ( 0x00000800 )
#define WDT_RWDT_CONFIG0_PROCPU_RESET_EN_VALUE(raw) ( ((raw) & (WDT_RWDT_CONFIG0_PROCPU_RESET_EN_MASK)) >> (WDT_RWDT_CONFIG0_PROCPU_RESET_EN_SHIFT) )
#define WDT_RWDT_CONFIG0_PROCPU_RESET_EN_RAW(value) ( (value) << (WDT_RWDT_CONFIG0_PROCPU_RESET_EN_SHIFT) )

#define WDT_RWDT_CONFIG0_FLASHBOOT_MOD_EN_DESC       "Configure whether or not to enable RWDT when chip is in SPI boot mode."
#define WDT_RWDT_CONFIG0_FLASHBOOT_MOD_EN_SHIFT      ( 12 )
#define WDT_RWDT_CONFIG0_FLASHBOOT_MOD_EN_MASK       ( 0x00001000 )
#define WDT_RWDT_CONFIG0_FLASHBOOT_MOD_EN_VALUE(raw) ( ((raw) & (WDT_RWDT_CONFIG0_FLASHBOOT_MOD_EN_MASK)) >> (WDT_RWDT_CONFIG0_FLASHBOOT_MOD_EN_SHIFT) )
#define WDT_RWDT_CONFIG0_FLASHBOOT_MOD_EN_RAW(value) ( (value) << (WDT_RWDT_CONFIG0_FLASHBOOT_MOD_EN_SHIFT) )

#define WDT_RWDT_CONFIG0_SYS_RESET_LENGTH_DESC       "Configure the core reset time. Measurement unit: LP_DYN_FAST_CLK"
#define WDT_RWDT_CONFIG0_SYS_RESET_LENGTH_SHIFT      ( 13 )
#define WDT_RWDT_CONFIG0_SYS_RESET_LENGTH_MASK       ( 0x0000E000 )
#define WDT_RWDT_CONFIG0_SYS_RESET_LENGTH_VALUE(raw) ( ((raw) & (WDT_RWDT_CONFIG0_SYS_RESET_LENGTH_MASK)) >> (WDT_RWDT_CONFIG0_SYS_RESET_LENGTH_SHIFT) )
#define WDT_RWDT_CONFIG0_SYS_RESET_LENGTH_RAW(value) ( (value) << (WDT_RWDT_CONFIG0_SYS_RESET_LENGTH_SHIFT) )

#define WDT_RWDT_CONFIG0_CPU_RESET_LENGTH_DESC       "Configure the CPU reset time. Measurement unit: LP_DYN_FAST_CLK"
#define WDT_RWDT_CONFIG0_CPU_RESET_LENGTH_SHIFT      ( 16 )
#define WDT_RWDT_CONFIG0_CPU_RESET_LENGTH_MASK       ( 0x00070000 )
#define WDT_RWDT_CONFIG0_CPU_RESET_LENGTH_VALUE(raw) ( ((raw) & (WDT_RWDT_CONFIG0_CPU_RESET_LENGTH_MASK)) >> (WDT_RWDT_CONFIG0_CPU_RESET_LENGTH_SHIFT) )
#define WDT_RWDT_CONFIG0_CPU_RESET_LENGTH_RAW(value) ( (value) << (WDT_RWDT_CONFIG0_CPU_RESET_LENGTH_SHIFT) )

#define WDT_RWDT_CONFIG0_STG3_DESC       "Configure the timeout action of stage3."
#define WDT_RWDT_CONFIG0_STG3_SHIFT      ( 19 )
#define WDT_RWDT_CONFIG0_STG3_MASK       ( 0x00380000 )
#define WDT_RWDT_CONFIG0_STG3_VALUE(raw) ( ((raw) & (WDT_RWDT_CONFIG0_STG3_MASK)) >> (WDT_RWDT_CONFIG0_STG3_SHIFT) )
#define WDT_RWDT_CONFIG0_STG3_RAW(value) ( (value) << (WDT_RWDT_CONFIG0_STG3_SHIFT) )

#define WDT_RWDT_CONFIG0_STG2_DESC       "Configure the timeout action of stage2."
#define WDT_RWDT_CONFIG0_STG2_SHIFT      ( 22 )
#define WDT_RWDT_CONFIG0_STG2_MASK       ( 0x01C00000 )
#define WDT_RWDT_CONFIG0_STG2_VALUE(raw) ( ((raw) & (WDT_RWDT_CONFIG0_STG2_MASK)) >> (WDT_RWDT_CONFIG0_STG2_SHIFT) )
#define WDT_RWDT_CONFIG0_STG2_RAW(value) ( (value) << (WDT_RWDT_CONFIG0_STG2_SHIFT) )

#define WDT_RWDT_CONFIG0_STG1_DESC       "Configure the timeout action of stage1."
#define WDT_RWDT_CONFIG0_STG1_SHIFT      ( 25 )
#define WDT_RWDT_CONFIG0_STG1_MASK       ( 0x0E000000 )
#define WDT_RWDT_CONFIG0_STG1_VALUE(raw) ( ((raw) & (WDT_RWDT_CONFIG0_STG1_MASK)) >> (WDT_RWDT_CONFIG0_STG1_SHIFT) )
#define WDT_RWDT_CONFIG0_STG1_RAW(value) ( (value) << (WDT_RWDT_CONFIG0_STG1_SHIFT) )

#define WDT_RWDT_CONFIG0_STG0_DESC       "Configure the timeout action of stage0."
#define WDT_RWDT_CONFIG0_STG0_SHIFT      ( 28 )
#define WDT_RWDT_CONFIG0_STG0_MASK       ( 0x70000000 )
#define WDT_RWDT_CONFIG0_STG0_VALUE(raw) ( ((raw) & (WDT_RWDT_CONFIG0_STG0_MASK)) >> (WDT_RWDT_CONFIG0_STG0_SHIFT) )
#define WDT_RWDT_CONFIG0_STG0_RAW(value) ( (value) << (WDT_RWDT_CONFIG0_STG0_SHIFT) )

#define WDT_RWDT_CONFIG0_EN_DESC       "Configure whether or not enable RWDT."
#define WDT_RWDT_CONFIG0_EN_SHIFT      ( 31 )
#define WDT_RWDT_CONFIG0_EN_MASK       ( 0x80000000 )
#define WDT_RWDT_CONFIG0_EN_VALUE(raw) ( ((raw) & (WDT_RWDT_CONFIG0_EN_MASK)) >> (WDT_RWDT_CONFIG0_EN_SHIFT) )
#define WDT_RWDT_CONFIG0_EN_RAW(value) ( (value) << (WDT_RWDT_CONFIG0_EN_SHIFT) )

// WDT_RWDT_CONFIG1
#define WDT_RWDT_CONFIG1_DESC "Configure the RWDT timeout time of stage0"

#ifndef __ASSEMBLY__

union wdt_rwdt_config1 {
	uint32_t raw;

	struct {
		uint32_t stg0_hold : 32;
	};
};

#endif // __ASSEMBLY__

#define WDT_RWDT_CONFIG1_STG0_HOLD_DESC       "Configure the timeout time for stage0. Measurement unit: LP_DYN_SLOW_CLK"
#define WDT_RWDT_CONFIG1_STG0_HOLD_SHIFT      ( 0 )
#define WDT_RWDT_CONFIG1_STG0_HOLD_MASK       ( 0xFFFFFFFF )
#define WDT_RWDT_CONFIG1_STG0_HOLD_VALUE(raw) ( ((raw) & (WDT_RWDT_CONFIG1_STG0_HOLD_MASK)) >> (WDT_RWDT_CONFIG1_STG0_HOLD_SHIFT) )
#define WDT_RWDT_CONFIG1_STG0_HOLD_RAW(value) ( (value) << (WDT_RWDT_CONFIG1_STG0_HOLD_SHIFT) )

// WDT_RWDT_CONFIG2
#define WDT_RWDT_CONFIG2_DESC "Configure the RWDT timeout time of stage1"

#ifndef __ASSEMBLY__

union wdt_rwdt_config2 {
	uint32_t raw;

	struct {
		uint32_t stg1_hold : 32;
	};
};

#endif // __ASSEMBLY__

#define WDT_RWDT_CONFIG2_STG1_HOLD_DESC       "Configure the timeout time for stage1. Measurement unit: LP_DYN_SLOW_CLK"
#define WDT_RWDT_CONFIG2_STG1_HOLD_SHIFT      ( 0 )
#define WDT_RWDT_CONFIG2_STG1_HOLD_MASK       ( 0xFFFFFFFF )
#define WDT_RWDT_CONFIG2_STG1_HOLD_VALUE(raw) ( ((raw) & (WDT_RWDT_CONFIG2_STG1_HOLD_MASK)) >> (WDT_RWDT_CONFIG2_STG1_HOLD_SHIFT) )
#define WDT_RWDT_CONFIG2_STG1_HOLD_RAW(value) ( (value) << (WDT_RWDT_CONFIG2_STG1_HOLD_SHIFT) )

// WDT_RWDT_CONFIG3
#define WDT_RWDT_CONFIG3_DESC "Configure the RWDT timeout time of stage2"

#ifndef __ASSEMBLY__

union wdt_rwdt_config3 {
	uint32_t raw;

	struct {
		uint32_t stg2_hold : 32;
	};
};

#endif // __ASSEMBLY__

#define WDT_RWDT_CONFIG3_STG2_HOLD_DESC       "Configure the timeout time for stage2. Measurement unit: LP_DYN_SLOW_CLK"
#define WDT_RWDT_CONFIG3_STG2_HOLD_SHIFT      ( 0 )
#define WDT_RWDT_CONFIG3_STG2_HOLD_MASK       ( 0xFFFFFFFF )
#define WDT_RWDT_CONFIG3_STG2_HOLD_VALUE(raw) ( ((raw) & (WDT_RWDT_CONFIG3_STG2_HOLD_MASK)) >> (WDT_RWDT_CONFIG3_STG2_HOLD_SHIFT) )
#define WDT_RWDT_CONFIG3_STG2_HOLD_RAW(value) ( (value) << (WDT_RWDT_CONFIG3_STG2_HOLD_SHIFT) )

// WDT_RWDT_CONFIG4
#define WDT_RWDT_CONFIG4_DESC "Configure the RWDT timeout time of stage3"

#ifndef __ASSEMBLY__

union wdt_rwdt_config4 {
	uint32_t raw;

	struct {
		uint32_t stg3_hold : 32;
	};
};

#endif // __ASSEMBLY__

#define WDT_RWDT_CONFIG4_STG3_HOLD_DESC       "Configure the timeout time for stage3. Measurement unit: LP_DYN_SLOW_CLK"
#define WDT_RWDT_CONFIG4_STG3_HOLD_SHIFT      ( 0 )
#define WDT_RWDT_CONFIG4_STG3_HOLD_MASK       ( 0xFFFFFFFF )
#define WDT_RWDT_CONFIG4_STG3_HOLD_VALUE(raw) ( ((raw) & (WDT_RWDT_CONFIG4_STG3_HOLD_MASK)) >> (WDT_RWDT_CONFIG4_STG3_HOLD_SHIFT) )
#define WDT_RWDT_CONFIG4_STG3_HOLD_RAW(value) ( (value) << (WDT_RWDT_CONFIG4_STG3_HOLD_SHIFT) )

// WDT_RWDT_FEED
#define WDT_RWDT_FEED_DESC "Configure the feed function of RWDT"

#ifndef __ASSEMBLY__

union wdt_rwdt_feed {
	uint32_t raw;

	struct {
		uint32_t rsvd0 : 31;
		uint32_t feed  : 1;
	};
};

#endif // __ASSEMBLY__

#define WDT_RWDT_FEED_FEED_DESC       "Configure this bit to feed the RWDT."
#define WDT_RWDT_FEED_FEED_SHIFT      ( 31 )
#define WDT_RWDT_FEED_FEED_MASK       ( 0x80000000 )
#define WDT_RWDT_FEED_FEED_VALUE(raw) ( ((raw) & (WDT_RWDT_FEED_FEED_MASK)) >> (WDT_RWDT_FEED_FEED_SHIFT) )
#define WDT_RWDT_FEED_FEED_RAW(value) ( (value) << (WDT_RWDT_FEED_FEED_SHIFT) )

// WDT_RWDT_WPROTECT
#define WDT_RWDT_WPROTECT_DESC "Configure the lock function of RWDT"

#ifndef __ASSEMBLY__

union wdt_rwdt_wprotect {
	uint32_t raw;

	struct {
		uint32_t wkey : 32;
	};
};

#endif // __ASSEMBLY__

#define WDT_RWDT_WPROTECT_WKEY_DESC       "Configure this field to lock or unlock RWDT’s configuration registers. 0x50D83AA1: unlock the RWDT configuration register. Others value: lock the RWDT configuration register which can’t be modified by software."
#define WDT_RWDT_WPROTECT_WKEY_SHIFT      ( 0 )
#define WDT_RWDT_WPROTECT_WKEY_MASK       ( 0xFFFFFFFF )
#define WDT_RWDT_WPROTECT_WKEY_VALUE(raw) ( ((raw) & (WDT_RWDT_WPROTECT_WKEY_MASK)) >> (WDT_RWDT_WPROTECT_WKEY_SHIFT) )
#define WDT_RWDT_WPROTECT_WKEY_RAW(value) ( (value) << (WDT_RWDT_WPROTECT_WKEY_SHIFT) )

// WDT_SWD_CONFIG
#define WDT_SWD_CONFIG_DESC "Configure the SWD operation"

#ifndef __ASSEMBLY__

union wdt_swd_config {
	uint32_t raw;

	struct {
		uint32_t reset_flag   : 1;
		uint32_t rsvd0        : 17;
		uint32_t auto_feed_en : 1;
		uint32_t rst_flag_clr : 1;
		uint32_t signal_width : 10;
		uint32_t disable      : 1;
		uint32_t feed         : 1;
	};
};

#endif // __ASSEMBLY__

#define WDT_SWD_CONFIG_RESET_FLAG_DESC       "Represents the SWD whether or not generate the reset signal"
#define WDT_SWD_CONFIG_RESET_FLAG_SHIFT      ( 0 )
#define WDT_SWD_CONFIG_RESET_FLAG_MASK       ( 0x00000001 )
#define WDT_SWD_CONFIG_RESET_FLAG_VALUE(raw) ( ((raw) & (WDT_SWD_CONFIG_RESET_FLAG_MASK)) >> (WDT_SWD_CONFIG_RESET_FLAG_SHIFT) )
#define WDT_SWD_CONFIG_RESET_FLAG_RAW(value) ( (value) << (WDT_SWD_CONFIG_RESET_FLAG_SHIFT) )

#define WDT_SWD_CONFIG_AUTO_FEED_EN_DESC       "Configure this bit to enable to feed SWD automatically by hardware."
#define WDT_SWD_CONFIG_AUTO_FEED_EN_SHIFT      ( 18 )
#define WDT_SWD_CONFIG_AUTO_FEED_EN_MASK       ( 0x00040000 )
#define WDT_SWD_CONFIG_AUTO_FEED_EN_VALUE(raw) ( ((raw) & (WDT_SWD_CONFIG_AUTO_FEED_EN_MASK)) >> (WDT_SWD_CONFIG_AUTO_FEED_EN_SHIFT) )
#define WDT_SWD_CONFIG_AUTO_FEED_EN_RAW(value) ( (value) << (WDT_SWD_CONFIG_AUTO_FEED_EN_SHIFT) )

#define WDT_SWD_CONFIG_RST_FLAG_CLR_DESC       "Configure this bit to clear SWD reset flag"
#define WDT_SWD_CONFIG_RST_FLAG_CLR_SHIFT      ( 19 )
#define WDT_SWD_CONFIG_RST_FLAG_CLR_MASK       ( 0x00080000 )
#define WDT_SWD_CONFIG_RST_FLAG_CLR_VALUE(raw) ( ((raw) & (WDT_SWD_CONFIG_RST_FLAG_CLR_MASK)) >> (WDT_SWD_CONFIG_RST_FLAG_CLR_SHIFT) )
#define WDT_SWD_CONFIG_RST_FLAG_CLR_RAW(value) ( (value) << (WDT_SWD_CONFIG_RST_FLAG_CLR_SHIFT) )

#define WDT_SWD_CONFIG_SIGNAL_WIDTH_DESC       "Confgure the SWD signal length that output to analog circuit. Measurement unit: LP_DYN_FAST_CLK (R/W)"
#define WDT_SWD_CONFIG_SIGNAL_WIDTH_SHIFT      ( 20 )
#define WDT_SWD_CONFIG_SIGNAL_WIDTH_MASK       ( 0x3FF00000 )
#define WDT_SWD_CONFIG_SIGNAL_WIDTH_VALUE(raw) ( ((raw) & (WDT_SWD_CONFIG_SIGNAL_WIDTH_MASK)) >> (WDT_SWD_CONFIG_SIGNAL_WIDTH_SHIFT) )
#define WDT_SWD_CONFIG_SIGNAL_WIDTH_RAW(value) ( (value) << (WDT_SWD_CONFIG_SIGNAL_WIDTH_SHIFT) )

#define WDT_SWD_CONFIG_DISABLE_DESC       "Configure this bit to disable the SWD."
#define WDT_SWD_CONFIG_DISABLE_SHIFT      ( 30 )
#define WDT_SWD_CONFIG_DISABLE_MASK       ( 0x40000000 )
#define WDT_SWD_CONFIG_DISABLE_VALUE(raw) ( ((raw) & (WDT_SWD_CONFIG_DISABLE_MASK)) >> (WDT_SWD_CONFIG_DISABLE_SHIFT) )
#define WDT_SWD_CONFIG_DISABLE_RAW(value) ( (value) << (WDT_SWD_CONFIG_DISABLE_SHIFT) )

#define WDT_SWD_CONFIG_FEED_DESC       "Configure this bit to feed the SWD."
#define WDT_SWD_CONFIG_FEED_SHIFT      ( 31 )
#define WDT_SWD_CONFIG_FEED_MASK       ( 0x80000000 )
#define WDT_SWD_CONFIG_FEED_VALUE(raw) ( ((raw) & (WDT_SWD_CONFIG_FEED_MASK)) >> (WDT_SWD_CONFIG_FEED_SHIFT) )
#define WDT_SWD_CONFIG_FEED_RAW(value) ( (value) << (WDT_SWD_CONFIG_FEED_SHIFT) )

// WDT_SWD_WPROTECT
#define WDT_SWD_WPROTECT_DESC "Configure the lock function of SWD"

#ifndef __ASSEMBLY__

union wdt_swd_wprotect {
	uint32_t raw;

	struct {
		uint32_t wkey : 32;
	};
};

#endif // __ASSEMBLY__

#define WDT_SWD_WPROTECT_WKEY_DESC       "Configure this field to lock or unlock SWD’s configuration registers. 0x50D83AA1: unlock the SWD configuration register. Others value: lock the SWD configuration register which can’t be modified by the software."
#define WDT_SWD_WPROTECT_WKEY_SHIFT      ( 0 )
#define WDT_SWD_WPROTECT_WKEY_MASK       ( 0xFFFFFFFF )
#define WDT_SWD_WPROTECT_WKEY_VALUE(raw) ( ((raw) & (WDT_SWD_WPROTECT_WKEY_MASK)) >> (WDT_SWD_WPROTECT_WKEY_SHIFT) )
#define WDT_SWD_WPROTECT_WKEY_RAW(value) ( (value) << (WDT_SWD_WPROTECT_WKEY_SHIFT) )

// WDT_INT_RAW
#define WDT_INT_RAW_DESC "The interrupt raw register of WDT"

#ifndef __ASSEMBLY__

union wdt_int_raw {
	uint32_t raw;

	struct {
		uint32_t rsvd0 : 30;
		uint32_t swd   : 1;
		uint32_t rwdt  : 1;
	};
};

#endif // __ASSEMBLY__

#define WDT_INT_RAW_SWD_DESC       "Represents the SWD whether or not generates timeout interrupt."
#define WDT_INT_RAW_SWD_SHIFT      ( 30 )
#define WDT_INT_RAW_SWD_MASK       ( 0x40000000 )
#define WDT_INT_RAW_SWD_VALUE(raw) ( ((raw) & (WDT_INT_RAW_SWD_MASK)) >> (WDT_INT_RAW_SWD_SHIFT) )
#define WDT_INT_RAW_SWD_RAW(value) ( (value) << (WDT_INT_RAW_SWD_SHIFT) )

#define WDT_INT_RAW_RWDT_DESC       "Represents the RWDT whether or not generates timeout interrupt."
#define WDT_INT_RAW_RWDT_SHIFT      ( 31 )
#define WDT_INT_RAW_RWDT_MASK       ( 0x80000000 )
#define WDT_INT_RAW_RWDT_VALUE(raw) ( ((raw) & (WDT_INT_RAW_RWDT_MASK)) >> (WDT_INT_RAW_RWDT_SHIFT) )
#define WDT_INT_RAW_RWDT_RAW(value) ( (value) << (WDT_INT_RAW_RWDT_SHIFT) )

// WDT_INT_ST
#define WDT_INT_ST_DESC "The interrupt status register of WDT"

#ifndef __ASSEMBLY__

union wdt_int_st {
	uint32_t raw;

	struct {
		uint32_t rsvd0 : 30;
		uint32_t swd   : 1;
		uint32_t rwdt  : 1;
	};
};

#endif // __ASSEMBLY__

#define WDT_INT_ST_SWD_DESC       "Represents the SWD whether or not generates and sends timeout interrupt to CPU."
#define WDT_INT_ST_SWD_SHIFT      ( 30 )
#define WDT_INT_ST_SWD_MASK       ( 0x40000000 )
#define WDT_INT_ST_SWD_VALUE(raw) ( ((raw) & (WDT_INT_ST_SWD_MASK)) >> (WDT_INT_ST_SWD_SHIFT) )
#define WDT_INT_ST_SWD_RAW(value) ( (value) << (WDT_INT_ST_SWD_SHIFT) )

#define WDT_INT_ST_RWDT_DESC       "Represents the RWDT whether or not generates and sends timeout interrupt to CPU."
#define WDT_INT_ST_RWDT_SHIFT      ( 31 )
#define WDT_INT_ST_RWDT_MASK       ( 0x80000000 )
#define WDT_INT_ST_RWDT_VALUE(raw) ( ((raw) & (WDT_INT_ST_RWDT_MASK)) >> (WDT_INT_ST_RWDT_SHIFT) )
#define WDT_INT_ST_RWDT_RAW(value) ( (value) << (WDT_INT_ST_RWDT_SHIFT) )

// WDT_INT_ENA
#define WDT_INT_ENA_DESC "The interrupt enable register of WDT"

#ifndef __ASSEMBLY__

union wdt_int_ena {
	uint32_t raw;

	struct {
		uint32_t rsvd0 : 30;
		uint32_t swd   : 1;
		uint32_t rwdt  : 1;
	};
};

#endif // __ASSEMBLY__

#define WDT_INT_ENA_SWD_DESC       "Configure whether or not to enable the SWD to send timeout interrupt."
#define WDT_INT_ENA_SWD_SHIFT      ( 30 )
#define WDT_INT_ENA_SWD_MASK       ( 0x40000000 )
#define WDT_INT_ENA_SWD_VALUE(raw) ( ((raw) & (WDT_INT_ENA_SWD_MASK)) >> (WDT_INT_ENA_SWD_SHIFT) )
#define WDT_INT_ENA_SWD_RAW(value) ( (value) << (WDT_INT_ENA_SWD_SHIFT) )

#define WDT_INT_ENA_RWDT_DESC       "Configure whether or not to enable the RWDT to send timeout interrupt."
#define WDT_INT_ENA_RWDT_SHIFT      ( 31 )
#define WDT_INT_ENA_RWDT_MASK       ( 0x80000000 )
#define WDT_INT_ENA_RWDT_VALUE(raw) ( ((raw) & (WDT_INT_ENA_RWDT_MASK)) >> (WDT_INT_ENA_RWDT_SHIFT) )
#define WDT_INT_ENA_RWDT_RAW(value) ( (value) << (WDT_INT_ENA_RWDT_SHIFT) )

// WDT_INT_CLR
#define WDT_INT_CLR_DESC "The interrupt clear register of WDT"

#ifndef __ASSEMBLY__

union wdt_int_clr {
	uint32_t raw;

	struct {
		uint32_t rsvd0 : 30;
		uint32_t swd   : 1;
		uint32_t rwdt  : 1;
	};
};

#endif // __ASSEMBLY__

#define WDT_INT_CLR_SWD_DESC       "Configure whether to clear the timeout interrupt signal sent by SWD to CPU."
#define WDT_INT_CLR_SWD_SHIFT      ( 30 )
#define WDT_INT_CLR_SWD_MASK       ( 0x40000000 )
#define WDT_INT_CLR_SWD_VALUE(raw) ( ((raw) & (WDT_INT_CLR_SWD_MASK)) >> (WDT_INT_CLR_SWD_SHIFT) )
#define WDT_INT_CLR_SWD_RAW(value) ( (value) << (WDT_INT_CLR_SWD_SHIFT) )

#define WDT_INT_CLR_RWDT_DESC       "Configure whether to clear the timeout interrupt signal sent by RWDT to CPU."
#define WDT_INT_CLR_RWDT_SHIFT      ( 31 )
#define WDT_INT_CLR_RWDT_MASK       ( 0x80000000 )
#define WDT_INT_CLR_RWDT_VALUE(raw) ( ((raw) & (WDT_INT_CLR_RWDT_MASK)) >> (WDT_INT_CLR_RWDT_SHIFT) )
#define WDT_INT_CLR_RWDT_RAW(value) ( (value) << (WDT_INT_CLR_RWDT_SHIFT) )

// WDT_DATE
#define WDT_DATE_DESC "Version control register"

#ifndef __ASSEMBLY__

union wdt_date {
	uint32_t raw;

	struct {
		uint32_t date   : 31;
		uint32_t clk_en : 1;
	};
};

#endif // __ASSEMBLY__

#define WDT_DATE_DATE_DESC       "Version control register"
#define WDT_DATE_DATE_SHIFT      ( 0 )
#define WDT_DATE_DATE_MASK       ( 0x7FFFFFFF )
#define WDT_DATE_DATE_VALUE(raw) ( ((raw) & (WDT_DATE_DATE_MASK)) >> (WDT_DATE_DATE_SHIFT) )
#define WDT_DATE_DATE_RAW(value) ( (value) << (WDT_DATE_DATE_SHIFT) )

#define WDT_DATE_CLK_EN_DESC       "Reserved"
#define WDT_DATE_CLK_EN_SHIFT      ( 31 )
#define WDT_DATE_CLK_EN_MASK       ( 0x80000000 )
#define WDT_DATE_CLK_EN_VALUE(raw) ( ((raw) & (WDT_DATE_CLK_EN_MASK)) >> (WDT_DATE_CLK_EN_SHIFT) )
#define WDT_DATE_CLK_EN_RAW(value) ( (value) << (WDT_DATE_CLK_EN_SHIFT) )

/* clang-format on */

#endif // WDT_REGS_H
