import argparse
import hashlib
import json
import toml
import sys
import os
import re


def parse_toml_file(file_path):
    try:
        with open(file_path, mode="r", encoding="utf-8") as f:
            data = toml.load(f)
            return data

    except Exception as e:
        print(f"{e}")
        sys.exit(1)


def parse_bit_range(bits_str):
    match = re.match(r"(\d+):(\d+)", bits_str)
    if match:
        return (int(match.group(1)), int(match.group(2)))
    try:
        bit = int(bits_str)
        return (bit, bit)
    except ValueError:
        return (None, None)


def get_bit_mask(msb, lsb):
    if msb is None or lsb is None or msb < lsb:
        return 0

    width = msb - lsb + 1
    mask = (1 << width) - 1
    return mask << lsb


def generate_cheader(data):
    desc = data.get("desc")
    prefix = data.get("prefix")
    regs = data.get("regs", [])

    header_guard = f"{prefix}_REGS_H"

    hasher = hashlib.sha256()
    hasher.update(json.dumps(data).encode("utf-8"))
    hash_value = hasher.hexdigest()

    content = "// Do not edit: This file is automatically generated\n"
    content += f"// hash: {hash_value}\n"
    content += f"// description: {desc}\n\n"

    content += f"#ifndef {header_guard}\n"
    content += f"#define {header_guard}\n\n"
    content += f"#include <stdint.h>\n\n"

    content += "/* clang-format off */\n\n"

    padding = 0
    for reg in regs:
        padding = max(padding, len(reg["name"]))

    content += "//Register Offsets\n\n"
    for reg in regs:
        reg_name = reg["name"]
        reg_offset = reg["offset"]
        reg_desc = reg["desc"]

        postfix = "OFS"
        macro_padding = padding + len(prefix) + len(postfix) + 2
        macro_name = f"{prefix}_{reg_name}_{postfix}".ljust(macro_padding)
        macro_value = f"0x{reg_offset:04X}UL"

        content += f"#define {macro_name} ( {macro_value} ) // {reg_desc}\n"

    content += "\n"
    content += "// Register REGs\n\n"
    for reg in regs:
        reg_name = reg["name"]
        reg_offset = reg["offset"]

        postfix = "REG(base)"
        macro_padding = padding + len(prefix) + len(postfix) + 2
        macro_name = f"{prefix}_{reg_name}_{postfix}".ljust(macro_padding)
        macro_padding = padding + len(prefix) + 16
        macro_value = f"(base) + ({prefix}_{reg_name}_OFS)".ljust(macro_padding)

        content += f"#define {macro_name} ( {macro_value} )\n"

    content += "\n"
    content += "// Register Bits\n\n"
    for reg in regs:
        reg_name = reg["name"]
        reg_desc = reg["desc"]
        reg_fields = reg.get("fields", [])

        content += f"// {prefix}_{reg_name}\n"
        content += f'#define {prefix}_{reg_name}_DESC "{reg_desc}"\n\n'

        content += "#ifndef __ASSEMBLY__\n\n"
        content += f"union {prefix.lower()}_{reg_name.lower()} "
        content += "{\n"
        content += "\tuint32_t raw;\n\n"
        content += "\tstruct {\n"

        field_padding = 0
        last_lsb = 0
        rsvd_cnt = 0
        for field in reg_fields:
            msb, lsb = parse_bit_range(field["bits"])
            if last_lsb < lsb:
                rsvd_cnt += 1

            last_lsb = msb + 1
            field_padding = max(field_padding, len(field["name"]))

        if last_lsb < 32:
            rsvd_cnt += 1

        if rsvd_cnt > 0:
            field_padding = max(field_padding, 4 + len(str(rsvd_cnt)))

        last_lsb = 0
        rsvd_idx = 0
        for field in reg_fields:
            field_name = field["name"].ljust(field_padding).lower()
            field_bits = field["bits"]

            msb, lsb = parse_bit_range(field_bits)
            if lsb is None:
                continue

            if last_lsb < lsb:
                rsvd = f"rsvd{rsvd_idx}".ljust(field_padding)
                content += f"\t\tuint32_t {rsvd} : {lsb - last_lsb};\n"
                rsvd_idx += 1

            content += f"\t\tuint32_t {field_name} : {msb - lsb + 1};\n"

            last_lsb = msb + 1

        if last_lsb < 32:
            rsvd = f"rsvd{rsvd_idx}".ljust(field_padding)
            content += f"\t\tuint32_t {rsvd} : {32 - last_lsb};\n"

        content += "\t};\n"
        content += "};\n\n"

        content += "#endif // __ASSEMBLY__\n\n"

        for field in reg_fields:
            field_name = field["name"]
            field_bits = field["bits"]
            field_desc = field["desc"]

            msb, lsb = parse_bit_range(field_bits)
            if lsb is None:
                continue

            field_mask = get_bit_mask(msb, lsb)
            field_mask = f"0x{field_mask:08X}"

            macro_name = f"{prefix}_{reg_name}_{field_name}"
            macro_padding = len(macro_name) + 11

            macro_desc = f"{macro_name}_DESC"
            macro_shift = f"{macro_name}_SHIFT"
            macro_mask = f"{macro_name}_MASK"
            macro_value = f"{macro_name}_VALUE(raw)"
            macro_raw = f"{macro_name}_RAW(value)"

            content += f'#define {macro_desc.ljust(macro_padding) } "{field_desc}"\n'
            content += f"#define {macro_shift.ljust(macro_padding)} ( {lsb} )\n"
            content += f"#define {macro_mask.ljust(macro_padding) } ( {field_mask} )\n"
            content += f"#define {macro_value.ljust(macro_padding)} ( ((raw) & ({macro_mask})) >> ({macro_shift}) )\n"
            content += f"#define {macro_raw.ljust(macro_padding)  } ( (value) << ({macro_shift}) )\n\n"

    content += "/* clang-format on */\n\n"

    content += f"#endif // {header_guard}\n"

    return content


def main():
    parser = argparse.ArgumentParser(description="Convert TOML file into (C Header, CSV, MarkDown) files")

    parser.add_argument("input_file", help="TOML input file")
    parser.add_argument("output_file", help="Output file")
    parser.add_argument(
        "-f",
        "--format",
        choices=["cheader", "csv", "md"],
        default="cheader",
        help="output file format",
    )

    args = parser.parse_args()

    data = parse_toml_file(args.input_file)

    if args.format == "cheader":
        content = generate_cheader(data)

        with open(args.output_file, "w", encoding="utf-8") as f:
            f.write(content)

    elif args.format == "csv":
        print("Not implemented")

    elif args.format == "md":
        print("Not implemented")


if __name__ == "__main__":
    main()
